---
title: "Figure 1: Burn conditions in the lab and field"
output:
  html_document:
    toc: yes
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, patchwork, pals, weathermetrics, lmerTest, pbkrtest, psych, broom,
                 lme4, MuMIn, merTools, Matrix, mvtnorm, matrixcalc)
  options(knitr.table.format = "latex")
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path = 'figures/', warning = FALSE,
                        message = FALSE, cache = FALSE)
```

# Import data

* firepower 
* flue temperature
* mce

```{r}
  lab_data <- readRDS("../../r_files/lab_temp_fp_mce_merged.RDS")
  samples <- readRDS("../../r_files/lab_samples.RDS")
  emissions_factors <- readRDS("../../r_files/lab_emissions_factors.RDS")
  #field_data <- readRDS("../../r_files/field_fp_mce_temp.RDS")
  #field_temp <- readRDS("../r_files/india_temp_merged.RDS")
  #field_fp <- readRDS("../r_files/field_firepower.RDS")
  #field_samples <- readRDS("../r_files/field_samples.RDS")
```

```{r}
  source("../../r_scripts/functions.r")
```

# Organize data

```{r}
  emissions_factors <-
    emissions_factors %>%
    dplyr::left_join(dplyr::select(samples, id, stove, fuel), by = "id") %>%
    dplyr::filter(fuel != "okote", fuel != "Eucalyptus (pellets)")
```

```{r}
  fuelcat_w = data.frame(fuel = c("Douglas fir (milled)",
                                "Eucalyptus (split)"), fuelcat = "Wood")

  fuelcat_c = data.frame(fuel = c("Coconut (briquettes)",
                                  "Hardwood (lumps)"), fuelcat = "Charcoal")
  
  fuelcat <-
    fuelcat_w %>%
    dplyr::bind_rows(fuelcat_c)
```

```{r}
  lab_data <-
    lab_data %>%
    dplyr::filter(fuel != "okote", fuel != "Eucalyptus (pellets)")
```

```{r}
  lab_data_der <-
    lab_data %>%
    tidyr::gather("var", "val", 6:8) %>%
    dplyr::group_by(stove, fuel, id, var) %>%
    dplyr::mutate(deriv = pad(diff(val, lag=1), length(val)) / 3 ) %>%
    dplyr::mutate(deriv2 = pad(diff(deriv, lag=1), length(val)) / 3 )

  mce <-
    lab_data_der %>%
    dplyr::ungroup() %>%
    dplyr::filter(var == "mce") %>%
    dplyr::rename("mce" = "val",
                  "dmce" = "deriv",
                  "d2mce" = "deriv2") %>%
    dplyr::select(id, datetime, mce, dmce, d2mce)
  
  fp <-
    lab_data_der %>%
    dplyr::ungroup() %>%
    dplyr::filter(var == "firepower") %>%
    dplyr::rename("fp" = "val",
                  "dfp" = "deriv",
                  "d2fp" = "deriv2") %>%
    dplyr::select(id, datetime, fp, dfp, d2fp)
```

```{r}
  bc <- 
    emissions_factors %>%
    dplyr::filter(pol == "bc", metric == "emissions_rate") %>%
    dplyr::mutate(val = val * 1e-3) %>%
    dplyr::filter(val > 0) %>%
    tidyr::spread(pol, val) %>%
    dplyr::left_join(mce, by = c("id", "datetime")) %>%
    dplyr::left_join(fp, by = c("id", "datetime")) %>%
    dplyr::left_join(fuelcat, by = "fuel") %>%
    dplyr::mutate("stove_fuel" = paste(stove, fuel))

  oa <- 
    emissions_factors %>%
    dplyr::filter(pol == "oa", metric == "emissions_rate") %>%
    dplyr::mutate(val = val * 1e-3) %>%
        dplyr::filter(val > 0) %>%
    tidyr::spread(pol, val) %>%
    dplyr::left_join(mce, by = c("id", "datetime")) %>%
    dplyr::left_join(fp, by = c("id", "datetime")) %>%
    dplyr::left_join(fuelcat, by = "fuel") %>%
    dplyr::mutate("stove_fuel" = paste(stove, fuel))

  ultrafines <- 
    emissions_factors %>%
    dplyr::filter(pol == "ultrafines", metric == "emissions_rate") %>%
    #dplyr::mutate(val = log10(val)) %>%
        dplyr::filter(val > 0) %>%
    tidyr::spread(pol, val) %>%
    dplyr::left_join(mce, by = c("id", "datetime")) %>%
    dplyr::left_join(fp, by = c("id", "datetime")) %>%
    dplyr::left_join(fuelcat, by = "fuel")  %>%
    dplyr::mutate("stove_fuel" = paste(stove, fuel))
```

# Linear models

## Black carbon

* Wood model

```{r}
  bc_wood <-
    bc %>%
    dplyr::select(id, datetime, fuelcat, bc, fp, mce, dfp, dmce, d2fp, d2mce, stove_fuel) %>%
    dplyr::filter(fuelcat == "Wood") %>%
    dplyr::mutate(fp = scale(fp, center = TRUE),
                  dfp = scale(dfp, center = TRUE),
                  d2fp = scale(d2fp, center = TRUE),
                  mce = scale(mce, center = TRUE),
                  dmce = scale(dmce, center = TRUE),
                  d2mce = scale(d2mce, center = TRUE))

  mod = lm(log(bc) ~ (fp + dfp + d2fp + mce + dmce + d2mce) * stove_fuel, data = bc_wood)
  summary(mod)
```

* Charcoal model

```{r}
  bc_charcoal <-
    bc %>%
    dplyr::select(id, datetime, fuelcat, bc, fp, mce, dfp, dmce, d2fp, d2mce, stove_fuel) %>%
    dplyr::filter(fuelcat == "Charcoal") %>%
    dplyr::mutate(fp = scale(fp, center = TRUE),
                  dfp = scale(dfp, center = TRUE),
                  d2fp = scale(d2fp, center = TRUE),
                  mce = scale(mce, center = TRUE),
                  dmce = scale(dmce, center = TRUE),
                  d2mce = scale(d2mce, center = TRUE))

  mod = lm(log(bc) ~ (fp + dfp + d2fp + mce + dmce + d2mce) * stove_fuel, data = bc_charcoal)
  summary(mod)
```

## Organic aerosol

* Wood model

```{r}
  oa_wood <-
    oa %>%
    dplyr::select(id, datetime, fuelcat, oa, fp, mce, dfp, dmce, d2fp, d2mce, stove_fuel) %>%
    dplyr::filter(fuelcat == "Wood") %>%
    dplyr::mutate(fp = scale(fp, center = TRUE),
                  dfp = scale(dfp, center = TRUE),
                  d2fp = scale(d2fp, center = TRUE),
                  mce = scale(mce, center = TRUE),
                  dmce = scale(dmce, center = TRUE),
                  d2mce = scale(d2mce, center = TRUE))

  mod = lm(log(oa) ~ (fp + dfp + d2fp + mce + dmce + d2mce) * stove_fuel, data = oa_wood)
  summary(mod)
```

* Charcoal model

```{r}
  oa_charcoal <-
    oa %>%
    dplyr::select(id, datetime, fuelcat, oa, fp, mce, dfp, dmce, d2fp, d2mce, stove_fuel) %>%
    dplyr::filter(fuelcat == "Charcoal") %>%
    dplyr::mutate(fp = scale(fp, center = TRUE),
                  dfp = scale(dfp, center = TRUE),
                  d2fp = scale(d2fp, center = TRUE),
                  mce = scale(mce, center = TRUE),
                  dmce = scale(dmce, center = TRUE),
                  d2mce = scale(d2mce, center = TRUE))

  mod = lm(log(oa) ~ (fp + dfp + d2fp + mce + dmce + d2mce) * stove_fuel, data = oa_charcoal)
  summary(mod)
```

## Ultrafine particles

* Wood model

```{r}
  ultrafines_wood <-
    ultrafines %>%
    dplyr::select(id, datetime, fuelcat, ultrafines, fp, mce, dfp, dmce, d2fp, d2mce, stove_fuel) %>%
    dplyr::filter(fuelcat == "Wood") %>%
    dplyr::mutate(fp = scale(fp, center = TRUE),
                  dfp = scale(dfp, center = TRUE),
                  d2fp = scale(d2fp, center = TRUE),
                  mce = scale(mce, center = TRUE),
                  dmce = scale(dmce, center = TRUE),
                  d2mce = scale(d2mce, center = TRUE))

  mod = lm(log(ultrafines) ~ (fp + dfp + d2fp + mce + dmce + d2mce) * stove_fuel, data = ultrafines_wood)
  summary(mod)
```

* Charcoal model

```{r}
  ultrafines_charcoal <-
    ultrafines %>%
    dplyr::select(id, datetime, fuelcat, ultrafines, fp, mce, dfp, dmce, d2fp, d2mce, stove_fuel) %>%
    dplyr::filter(fuelcat == "Charcoal") %>%
    dplyr::mutate(fp = scale(fp, center = TRUE),
                  dfp = scale(dfp, center = TRUE),
                  d2fp = scale(d2fp, center = TRUE),
                  mce = scale(mce, center = TRUE),
                  dmce = scale(dmce, center = TRUE),
                  d2mce = scale(d2mce, center = TRUE))

  mod = lm(log(ultrafines) ~ (fp + dfp + d2fp + mce + dmce + d2mce) * stove_fuel, data = ultrafines_charcoal)
  summary(mod)
```