---
title: "Notes qaqc"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

```{r load_libraries, include=FALSE}
  library(tidyverse)
  library(knitr)
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/', warning = FALSE, message = FALSE, cache = FALSE, tidy = TRUE)
```

# Load files

```{r load_files}
  notes <- readRDS("../r_files/field_notes.RDS")
  samples <- readRDS("../r_files/field_samples.RDS")
  flows <- readRDS("../r_files/field_inst_flows.RDS")
  filter_meta <- readRDS("../r_files/field_filter_meta.RDS")
  grav <- readRDS("../r_files/field_grav.RDS")
```

# Compile notes

## Metadata notes

```{r compile_notes}
  test_id_date <- dplyr::select(samples, hh_id, date)
  
  notes_1 <- dplyr::select(flows, hh_id, inst, notes) %>%
             dplyr::filter(!is.na(notes))
```

## Instrument notes

```{r grav_notes}
  notes_g1 <- dplyr::filter(filter_meta, grepl("Uncontrolled Test|Blank", filter_type)) %>%
              dplyr::select(-hh_id) %>%
              dplyr::left_join(test_id_date, by = "date") %>%
              dplyr::select(hh_id, notes, cart_id) %>%
              dplyr::filter(!is.na(notes)) %>%
              dplyr::mutate(inst = ifelse(grepl("^[A-Z][A-Z]$",cart_id),
                                          "grav:ecoc", "ecoc")) %>%
              dplyr::select(-cart_id)

  notes_g2 <- dplyr::select(grav, id, notes) %>%
              dplyr::filter(grepl("^IN[0-9]",id)) %>%  # only deals with emissions tests
              dplyr::left_join(dplyr::select(filter_meta, hh_id, filter_type, teflon_id),
                               by = c("id" = "teflon_id")) %>%
              dplyr::filter(notes != "") %>%
              dplyr::filter(!is.na(hh_id)) %>%
              dplyr::mutate(notes = paste0(filter_type, ": ", notes)) %>%
              dplyr::select(hh_id, notes) %>%
              dplyr::mutate(inst = "grav")
```

## Combine meta and inst notes

```{r combine_notes}
  inst_notes <- dplyr::bind_rows(notes_1, notes_g1, notes_g2)
```

## Create qc flag

With default value `maybe`.

```{r add_flag}
  inst_notes <- dplyr::mutate(inst_notes,
                              qc = factor("maybe", c("bad", "maybe", "ok")))
```

# Combine all notes

```{r bind_notes}
  notes <- dplyr::bind_rows(notes, inst_notes) %>%
           dplyr::mutate(hh_id = as.factor(hh_id))
```

# Adjust some flags based on notes

```{r adjust_flags}
  notes <- dplyr::mutate(notes, 
                         qc = ifelse(grepl("Filter damaged", notes),
                                     "bad", as.character(qc)))
```

# Save notes

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  saveRDS(notes, file = "../r_files/field_compiled_notes.RDS")
```
