---
title: "Field emissions factors"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

```{r load_libraries, include=FALSE}
  library(tidyverse)
  library(knitr)
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/', warning = FALSE, message = FALSE, cache = FALSE, tidy = TRUE)
```

# Load files

* functions 

```{r functions}
  source("../r_scripts/functions.R")
  source("../r_scripts/plots.R")
```

* pollutant data

```{r load_data}
  temp <- readRDS("../r_files/field_temp_merged.RDS")
  grav <- readRDS("../r_files/field_grav_merged.RDS")
  aqe <- readRDS("../r_files/field_aqe_merged.RDS")
  aqe_bkgd <- readRDS("../r_files/field_aqe_bkgd.RDS")
```

* constants

```{r load_constants}
  fuel_properties <- readRDS("../r_files/fuel_properties.RDS")
  pol_properties <- readRDS("../r_files/pol_properties.RDS")
```

* metadata

```{r load_metadata}
  times <- readRDS("../r_files/field_test_times.RDS")
```

# Gas analyzer

```{r aqe_test_avg}
  aqe <- aqe %>%
         dplyr::group_by(hh_id, var) %>%
         dplyr::summarise(mix_ratio = mean(val, na.rm = TRUE),
                          units = first(units),
                          qc = first(qc)) %>%
        dplyr::ungroup()
```

* convert mixing ratios to mass conc (assuming constant T and P)

```{r calc_mass_conc}
  aqe <- aqe %>%
         dplyr::left_join(pol_properties, by = c("var" = "pol")) %>%
         dplyr::mutate(mass_conc = convert_ppmv_ugm3(ppmv = mix_ratio, mw = mw)) %>%
         dplyr::select(-units, -num_c, -mw)
```

* extract test duration

```{r add_test_time}
  dur <- times %>%
         dplyr::filter(var == "dur") %>%
         tidyr::spread(var, value) %>%
         dplyr::select(hh_id, dur)
```

* merge with test duration

```{r add_test_time}
  aqe <- aqe %>%
         dplyr::left_join(dur)
```

* merge with background data

```{r add_bkgd}
  bkgd
```


