---
title: "Figure 5 for Firepower Sweep Paper"
output:
  html_document:
    toc: true
    toc_float: true
    theme: paper
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, patchwork)
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', warning=FALSE, message=FALSE, cache=FALSE, echo=FALSE)
```

```{r load_data}
  grav <- readRDS("../r_files/lab_grav_merged.RDS")
  wbt <- readRDS("../r_files/wbt_data_merged.RDS")
```

```{r}
  source("../r_scripts/functions.r")
```

```{r}
  grav <-
    grav %>%
    dplyr::filter(id != "3B", fuel != "okote")
```

```{r}
  continuous <- 
    grav %>%
    dplyr::filter(grepl("pm_ef|co_ef|fp|bc_ef", var), grepl("continuous", fst_type), !is.na(val), val > 0) %>%
    dplyr::select(-units) %>%
    tidyr::spread(var, val) %>%
    dplyr::mutate(phase = as.character(sample_id),
                  phase = ifelse(grepl("start_up", sample_id), "start-up", phase),
                  phase = ifelse(grepl("shutdown", sample_id), "shut-down", phase),
                  phase = ifelse(grepl("1|2|3|4", sample_id), "sweep-down", phase),
                  phase = ifelse(grepl("5|6|7", sample_id), "sweep-up", phase),
                  phase = forcats::fct_relevel(phase,
                                               "start-up",
                                                "sweep-down",
                                                "sweep-up",
                                                "shut-down"),
                  stove = forcats::fct_relevel(stove,
                                               "three-stone fire",
                                               "mud chulha",
                                               "metal grill",
                                               "rocket elbow",
                                               "ceramic plancha",
                                               "metal plancha"))
```

```{r}
  batch <- 
    grav %>%
    dplyr::filter(grepl("pm_ef|co_ef|fp|bc_ef|mce", var), grepl("batch", fst_type), !is.na(val), val > 0) %>%
    dplyr::select(-units) %>%
    tidyr::spread(var, val) %>%
    dplyr::mutate(phase = as.character(sample_id),
                  phase = ifelse(grepl("start_up", sample_id), "start-up", phase),
                  phase = ifelse(grepl("shutdown", sample_id), "shut-down", phase),
                  phase = ifelse(grepl("3", sample_id), "refuel", phase),
                  phase = ifelse(grepl("1|2", sample_id), "pre-refuel", phase),
                  phase = ifelse(grepl("4|5", sample_id), "post-refuel", phase)) %>%
  dplyr::mutate(stove = forcats::fct_relevel(stove,
                                             "ceramic jiko",
                                             "metal jiko",
                                             "forced-draft gasifier")) %>%
  dplyr::mutate(fuel = forcats::fct_relevel(fuel,
                                            "coconut (briquettes)",
                                            "hardwood (lump)",
                                            "eucalyptus (pellets)",
                                            "red oak (milled)")) %>%
  dplyr::mutate(phase = forcats::fct_relevel(phase,
                                              "start-up",
                                              "pre-refuel",
                                              "refuel",
                                              "post-refuel",
                                              "shut-down"))
```

```{r}
  wbt_plot <-
    wbt %>%
    dplyr::filter(grepl("pm2.5", pol), grepl("grams per kilogram", units)) %>%
    tidyr::spread(var, value) %>%
    dplyr::mutate(pm_min = mean - stdev, pm_max = mean + stdev) %>%
    dplyr::rename("pm_ef" = "mean") %>%
    dplyr::select(-stdev, -pol, -units, -ref, -n_test) %>%
    dplyr::left_join(wbt %>%
                     dplyr::select(id, stove, fuel, pol, var, value,
                                   fuel_notes, protocol, protocol_notes, units) %>%
                     dplyr::filter(grepl("co", pol), grepl("grams per kilogram", units)) %>%
                     tidyr::spread(var, value) %>%
                     dplyr::mutate(co_min = mean - stdev, co_max = mean + stdev) %>%
                     dplyr::rename("co_ef" = "mean") %>%
                     dplyr::select(-stdev, -pol, -units, -var),
                     by = c("id", "protocol", "stove", "fuel", "fuel_notes", "protocol_notes")) %>%
    dplyr::left_join(wbt %>%
                     dplyr::select(id, stove, fuel, pol, var, value,
                                   fuel_notes, protocol, protocol_notes, units) %>%
                     dplyr::filter(grepl("firepower", pol), grepl("watts", units)) %>%
                     dplyr::mutate(value = ifelse(units == "watts", value / 1000, value)) %>%
                     tidyr::spread(var, value) %>%
                     dplyr::mutate(fp_min = mean - stdev, fp_max = mean + stdev) %>%
                     dplyr::rename("fp" = "mean") %>%
                     dplyr::select(-stdev, -pol, -units),
                     by = c("id", "protocol", "stove", "fuel", "fuel_notes", "protocol_notes")) %>%
    dplyr::filter(fuel_notes != "wet", grepl("three|metal jiko|rocket|forced|plancha|ceramic jiko", stove)) %>%
    dplyr::mutate(phase = ifelse(grepl("simmer", protocol), "WBT: low power", "WBT: high power"))
```

```{r}
  wbt_cont <-
    wbt_plot %>%
    dplyr::filter(grepl("continuous", fst_type)) %>%
    dplyr::mutate(fuel = "")

  continuous <- 
    continuous %>%
    bind_rows(wbt_cont) %>%
    dplyr::mutate(phase = forcats::fct_expand(as_factor(phase),
                                              "start-up",
                                              "sweep-down",
                                              "sweep-up",
                                              "shut-down",
                                              "WBT: high power",
                                              "WBT: low power"),
                  phase = forcats::fct_relevel(phase,
                                               "start-up",
                                               "sweep-down",
                                               "sweep-up",
                                               "shut-down",
                                               "WBT: high power",
                                               "WBT: low power"),
                  stove = forcats::fct_relevel(stove,
                                               "three-stone fire",
                                               "mud chulha",
                                               "metal grill",
                                               "rocket elbow",
                                               "ceramic plancha",
                                               "metal plancha"))
    

  wbt_batch <-
    wbt_plot %>%
    dplyr::filter(grepl("batch", fst_type)) %>%
    dplyr::mutate(fuel = "")
  
  batch <-
    batch %>%
    bind_rows(wbt_batch) %>%
    dplyr::mutate(phase = forcats::fct_expand(as_factor(phase),
                                               "start-up",
                                               "pre-refuel",
                                               "refuel",
                                               "post-refuel",
                                               "shut-down",
                                               "WBT: high power",
                                               "WBT: low power"),
                  phase = forcats::fct_relevel(phase,
                                               "start-up",
                                               "pre-refuel",
                                               "refuel",
                                               "post-refuel",
                                               "shut-down",
                                               "WBT: high power",
                                               "WBT: low power"),
                  stove = forcats::fct_relevel(stove,
                                               "ceramic jiko",
                                               "metal jiko",
                                               "forced-draft gasifier"),
                  fuel = forcats::fct_relevel(fuel,
                                              "coconut (briquettes)",
                                              "hardwood (lump)",
                                              "eucalyptus (pellets)",
                                              "red oak (milled)"))
```

```{r}
    eqns <- by(continuous, continuous$fuel, pm_p)

    cont_fuel_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
                    dplyr::filter(!is.na(eq))
```

```{r}
    eqns <- by(batch, batch$fuel, pm_p)

    batch_fuel_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
                      dplyr::filter(!is.na(eq))
```

```{r}
    eucalyptus <-
      continuous %>%
      dplyr::filter(grepl("euc", fuel))

    eqns <- by(eucalyptus, eucalyptus$stove, pm_p)

    euc_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
              dplyr::filter(!is.na(eq))
```

```{r}
    fir <-
      continuous %>%
      dplyr::filter(grepl("fir", fuel))

    eqns <- by(fir, fir$stove, pm_p)

    fir_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
              dplyr::filter(!is.na(eq))
```

```{r}
  cont <-
    continuous %>%
    dplyr::filter(!grepl("plancha", stove))

    eqns <- by(cont, cont$stove, pm_p)

    cont_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
              dplyr::filter(!is.na(eq))
```

```{r}
    hardwood <-
      batch %>%
      dplyr::filter(grepl("hardwood", fuel))

    eqns <- by(hardwood, hardwood$stove, pm_p)

    hardwood_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
                   dplyr::filter(!is.na(eq))
```

```{r}
    coconut <-
      batch %>%
      dplyr::filter(grepl("coconut", fuel))

    eqns <- by(coconut, coconut$stove, pm_p)

    coconut_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
                  dplyr::filter(!is.na(eq))
```

```{r}
  eqns <- by(batch, batch$stove, pm_p)

  batch_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
              dplyr::filter(!is.na(eq))
```

```{r}
    oak <-
      batch %>%
      dplyr::filter(grepl("oak", fuel))

    eqns <- by(oak, oak$stove, pm_p)

    oak_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
              dplyr::filter(!is.na(eq))
```

```{r}
    pellets <-
      batch %>%
      dplyr::filter(grepl("euc", fuel))

    eqns <- by(pellets, pellets$stove, pm_p)

    pellets_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
                  dplyr::filter(!is.na(eq))
```

```{r}
  p1 <- 
    continuous %>%
      ggplot(aes(x = fp, y = (pm_ef), color = fuel)) +
        geom_point(aes(shape = phase), size = 3, alpha = 0.75, stroke = 1) +
        geom_text(data = fir_r2, aes(x = 7.5, y = 70, label = eq),
                  color = "#999999",  parse = TRUE, size = 5.5) +
        geom_text(data = euc_r2, aes(x = 7.5, y = 25, label = eq),
                  color = "#E69F00",  parse = TRUE, size = 5.5) +
        scale_y_continuous(breaks = c(0.1, 1, 10, 100),
                           limits = c(0.05, 100), trans = "log10") +
        scale_x_continuous(breaks = c(0, 2, 4, 6, 8, 10, 12, 14)) +
        geom_errorbar(aes(ymin = pm_min, ymax = pm_max),
                      width = 0, color = "black") +
        geom_errorbarh(aes(xmin = fp_min, xmax = fp_max),
                       height = 0, color = "black") +
        scale_color_manual(values = c("black", "#999999", "#E69F00")) +
        guides(color = guide_legend(override.aes = list(size = 3,
                                                        color = c("#FFFFFF", "#999999", "#E69F00")))) +
        scale_shape_manual(values = c(8, 1, 16, 4, 0, 2)) +
        theme_bw() +
        theme(text = element_text(size = 20),
              strip.background = element_rect(fill = "white"),
              plot.title = element_text(hjust = 0.5),
              legend.position = "right") +
          facet_wrap(~ stove, nrow = 2) +
          ggtitle("Continuous-Feed Wood Stoves") +
          xlab("Firepower (kW)") +
          ylab(expression(paste(PM[2.5], " Emissions Factors (g/kg-fuel)"))) +
          labs(shape = "", color = "")
```

```{r}
  p2 <-
    batch %>%
      ggplot(aes(x = fp, y = (pm_ef), color = fuel)) +
        geom_point(aes(shape = phase), alpha = 0.75, size = 3, stroke = 1) +
        geom_errorbar(aes(ymin = pm_min, ymax = pm_max),
                      width = 0, color = "black") +
        geom_errorbarh(aes(xmin = fp_min, xmax = fp_max),
                       height = 0, color = "black") +
        scale_y_continuous(breaks = c(0.1, 1, 10, 100),
                           limits = c(0.05, 100), trans = "log10") +
        geom_text(data = coconut_r2, aes(x = 6, y = 70, label = eq),
                  color = "yellowgreen",  parse = TRUE, size = 6) +
        geom_text(data = pellets_r2, aes(x = 6, y = 70, label = eq),
                  color = "coral3",  parse = TRUE, size = 6) +
        geom_text(data = hardwood_r2, aes(x = 6, y = 25, label = eq),
                  color = "darkcyan",  parse = TRUE, size = 6) +
        geom_text(data = oak_r2, aes(x = 6, y = 25, label = eq),
                  color = "#0072B2",  parse = TRUE, size = 6) +
        scale_color_manual(values = c("yellowgreen", "darkcyan", "coral3", "#0072B2", "black")) +
        guides(color = guide_legend(override.aes = list(size = 3,
                                                        color = c("yellowgreen", "darkcyan",
                                                                  "coral3", "#0072B2", "#FFFFFF")))) +
        scale_shape_manual(values = c(8, 1, 3, 16, 4, 0, 2)) +
        theme_bw() +
        theme(text = element_text(size = 20),
              strip.background = element_rect(fill = "white"),
              plot.title = element_text(hjust = 0.5),
              legend.position = "right") +
          facet_wrap(~stove, nrow = 1) +
          ggtitle("Batch-Fed Stoves") +
          xlab("Firepower (kW)") +
          ylab(expression(paste(PM[2.5], " Emissions Factors (g/kg-fuel)"))) +
          labs(color = "", shape = "")
```

```{r SI_1, echo=FALSE, fig.width=12, fig.height=12}
  p1 + p2 + plot_layout(ncol = 1, heights = c(2, 1))
```

```{r}
    eucalyptus <-
      continuous %>%
      dplyr::filter(grepl("euc", fuel))

    eqns <- by(eucalyptus, eucalyptus$stove, co_p)

    euc_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
              dplyr::filter(!is.na(eq))
```

```{r}
    fir <-
      continuous %>%
      dplyr::filter(grepl("fir", fuel))

    eqns <- by(fir, fir$stove, co_p)

    fir_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
              dplyr::filter(!is.na(eq))
```

```{r}
    hardwood <-
      batch %>%
      dplyr::filter(grepl("hardwood", fuel))

    eqns <- by(hardwood, hardwood$stove, co_p)

    hardwood_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
                   dplyr::filter(!is.na(eq))
```

```{r}
    coconut <-
      batch %>%
      dplyr::filter(grepl("coconut", fuel))

    eqns <- by(coconut, coconut$stove, co_p)

    coconut_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
                  dplyr::filter(!is.na(eq))
```

```{r}
    oak <-
      batch %>%
      dplyr::filter(grepl("oak", fuel))

    eqns <- by(oak, oak$stove, co_p)

    oak_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
              dplyr::filter(!is.na(eq))
```

```{r}
    pellets <-
      batch %>%
      dplyr::filter(grepl("euc", fuel))

    eqns <- by(pellets, pellets$stove, co_p)

    pellets_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
                  dplyr::filter(!is.na(eq))
```

```{r}
  p1 <- 
    continuous %>%
      ggplot(aes(x = fp, y = (co_ef), color = fuel)) +
        geom_point(aes(shape = phase), size = 3, alpha = 0.75, stroke = 1) +
        scale_y_continuous(breaks = c(1, 10, 100),
                           limits = c(1, 100), trans = "log10") +
        scale_x_continuous(breaks = c(0, 2, 4, 6, 8, 10, 12, 14)) +
        geom_text(data = fir_r2, aes(x = 7.5, y = 3, label = eq),
                  color = "#999999",  parse = TRUE, size = 5.5) +
        geom_text(data = euc_r2, aes(x = 7.5, y = 2, label = eq),
                  color = "#E69F00",  parse = TRUE, size = 5.5) +
        geom_errorbar(aes(ymin = co_min, ymax = co_max),
                      width = 0, color = "black") +
        geom_errorbarh(aes(xmin = fp_min, xmax = fp_max),
                       height = 0, color = "black") +
        scale_color_manual(values = c("black", "#999999", "#E69F00")) +
        guides(color = guide_legend(override.aes = list(size = 3,
                                                        color = c("#FFFFFF", "#999999", "#E69F00")))) +
        scale_shape_manual(values = c(8, 1, 16, 4, 0, 2)) +
        theme_bw() +
        theme(text = element_text(size = 20),
              strip.background = element_rect(fill = "white"),
              plot.title = element_text(hjust = 0.5),
              legend.position = "right") +
          facet_wrap(~ stove, nrow = 2) +
          ggtitle("Continuous-Feed Wood Stoves") +
          xlab("Firepower (kW)") +
          ylab(expression(paste(CO, " Emissions Factors (g/kg-fuel)"))) +
          labs(shape = "", color = "")
```

```{r}
  p2 <-
    batch %>%
      ggplot(aes(x = fp, y = (co_ef), color = fuel)) +
        scale_y_continuous(breaks = c(1, 10, 100),
                           limits = c(1, 500), trans = "log10") +
        geom_point(aes(shape = phase), alpha = 0.75, size = 3, stroke = 1) +
        geom_errorbar(aes(ymin = co_min, ymax = co_max),
                      width = 0, color = "black") +
        geom_errorbarh(aes(xmin = fp_min, xmax = fp_max),
                       height = 0, color = "black") +
        geom_text(data = coconut_r2, aes(x = 6, y = 3, label = eq),
                  color = "yellowgreen",  parse = TRUE, size = 6) +
        geom_text(data = pellets_r2, aes(x = 6, y = 300, label = eq),
                  color = "coral3",  parse = TRUE, size = 6) +
        geom_text(data = hardwood_r2, aes(x = 6, y = 2, label = eq),
                  color = "darkcyan",  parse = TRUE, size = 6) +
        geom_text(data = oak_r2, aes(x = 6, y = 200, label = eq),
                  color = "#0072B2",  parse = TRUE, size = 6) +
        scale_color_manual(values = c("yellowgreen", "darkcyan", "coral3", "#0072B2", "black")) +
        guides(color = guide_legend(override.aes = list(size = 3,
                                                        color = c("yellowgreen", "darkcyan",
                                                                  "coral3", "#0072B2", "#FFFFFF")))) +
        scale_shape_manual(values = c(8, 1, 3, 16, 4, 0, 2)) +
        theme_bw() +
        theme(text = element_text(size = 20),
              strip.background = element_rect(fill = "white"),
              plot.title = element_text(hjust = 0.5),
              legend.position = "right") +
          facet_wrap(~stove, nrow = 1) +
          ggtitle("Batch-Fed Stoves") +
          xlab("Firepower (kW)") +
          ylab(expression(paste(CO, " Emissions Factors (g/kg-fuel)"))) +
          labs(color = "", shape = "")
```

```{r SI_2, echo=FALSE, fig.width=12, fig.height=12}
  p1 + p2 + plot_layout(ncol = 1, heights = c(2, 1))
```

```{r}
    eucalyptus <-
      continuous %>%
      dplyr::filter(grepl("euc", fuel))

    eqns <- by(eucalyptus, eucalyptus$stove, bc_p)

    euc_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
              dplyr::filter(!is.na(eq))
```

```{r}
    fir <-
      continuous %>%
      dplyr::filter(grepl("fir", fuel))

    eqns <- by(fir, fir$stove, bc_p)

    fir_r2 <- data.frame(eq = unclass(eqns), stove = names(eqns)) %>%
              dplyr::filter(!is.na(eq))
```

```{r}
  p1 <- 
    continuous %>%
      ggplot(aes(x = fp, y = (bc_ef), color = fuel)) +
        geom_point(aes(shape = phase), size = 3, alpha = 0.75, stroke = 1) +
        scale_color_manual(values = c("#999999", "#E69F00")) +
        scale_y_continuous(breaks = c(0.1, 1, 10), limits = c(0.1, 10), trans = "log10") +
        scale_x_continuous(breaks = c(0, 2, 4, 6, 8, 10, 12, 14)) +
        geom_text(data = fir_r2, aes(x = 7.5, y = 5, label = eq),
                  color = "#999999",  parse = TRUE, size = 5.5) +
        geom_text(data = euc_r2, aes(x = 7.5, y = 2, label = eq),
                  color = "#E69F00",  parse = TRUE, size = 5.5) +
        scale_color_manual(values = c("black", "#999999", "#E69F00")) +
        guides(color = guide_legend(override.aes = list(size = 3,
                                                        color = c("#FFFFFF", "#999999", "#E69F00")))) +
        scale_shape_manual(values = c(8, 1, 16, 4, 0, 2)) +
        scale_shape_manual(values = c(8, 1, 16, 4, 0, 2)) +
        theme_bw() +
        theme(text = element_text(size = 20),
              strip.background = element_rect(fill = "white"),
              plot.title = element_text(hjust = 0.5),
              legend.position = "right") +
          facet_wrap(~ stove, nrow = 2) +
          ggtitle("Continuous-Feed Wood Stoves") +
          xlab("Firepower (kW)") +
          ylab(expression(paste(BC, " Emissions Factors (g/kg-fuel)"))) +
          labs(shape = "", color = "")
```

```{r SI_3, echo=FALSE, fig.width=12, fig.height=6}
  p1
```