---
title: "Firepower Paper Groupings"
output:
  html_document:
    toc: true
    toc_float: true
    theme: paper
---

```{r load_libraries, echo=FALSE, message=FALSE}
  library(tidyverse)
  library(forcats) #meow!
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', warning=FALSE, message=FALSE, cache=FALSE)
```

```{r load_data}
  samples <- readRDS("../r_files/lab_meta.RDS")
  wbt_data <- readRDS("../r_files/wbt_data.RDS")
  field_data <- readRDS("../r_files/field_data.RDS")
  rose_data <- readRDS("../r_files/rose_field_data.RDS")
```

# FST data

```{r fuel_type}
  samples <-
    samples %>%
    dplyr::mutate(fuel = gsub("Wood Pellets", "Eucalyptus Pellets", fuel),
                  fst_type = if_else(grepl("Lump Hardwood|Coconut Charcoal", fuel),
                                      "batch-fed\ncharcoal protocol",
                                      "continuous-feed\nwood protocol"),
                  fst_type = if_else(grepl("Red Oak|Eucalyptus Pellets", fuel),
                                      "batch-fed\nwood protocol", fst_type),
                  fst_type = as.factor(fst_type),
                  fst_type = fct_relevel(fst_type,
                                          "continuous-feed\nwood protocol",
                                          "batch-fed\ncharcoal protocol",
                                          "batch-fed\nwood protocol"),
                  test_type = "FST")
```

```{r}
  samples <-
    samples %>%
    dplyr::mutate(stove = tolower(stove),
                  fuel = tolower(fuel),
                  tester = tolower(tester)) %>%
          dplyr::mutate(stove =
                          stove %>%
                          forcats::fct_recode("Three-stone fire" = "three stone fire",
                                              "Metal plancha" = "justa (hm5000)",
                                              "Ceramic plancha" = "justa (artisan)",
                                              "Ceramic plancha" = "sunken pot",
                                              "Mud chulha" = "clay ring",
                                              "Metal grill" = "vikram", 
                                              "Rocket elbow" = "rocket elbow (g3300)",
                                              "Rocket elbow" = "rocket elbow (chulika)",
                                              "Ceramic jiko" = "ceramic jiko (small)",
                                              "Ceramic jiko" = "ceramic jiko (large)",
                                              "Metal jiko" = "metal jiko (small)",
                                              "Metal jiko" = "metal jiko (large)",
                                              "Metal jiko" = "metal jiko (burn)",
                                              "Forced-draft gasifier" = "gasifier (philips)",
                                              "Forced-draft gasifier" = "gasifier (doe)"),
                        fuel =
                          fuel %>%
                          forcats::fct_recode("Douglas fir (milled)" = "douglas fir",
                                              "Red oak (milled)" = "red oak",
                                              "Eucalyptus (split)" = "eucalyptus",
                                              "Eucalyptus (pellets)" = "eucalyptus pellets",
                                              "Hardwood (lumps)" = "lump hardwood",
                                              "Coconut (briquettes)" = "coconut charcoal"),
                        stove_cat = fct_collapse(stove,
                                                 "open fires" = c("Three-stone fire",
                                                                  "Mud chulha",
                                                                  "Metal grill"),
                                                 "improved stoves" = c("Rocket elbow"),
                                                 "chimney stoves" = c("Metal plancha",
                                                                      "Ceramic plancha"),
                                                 "charcoal stoves" = c("Metal jiko",
                                                                       "Ceramic jiko"),
                                                 "gasifiers" = c("Forced-draft gasifier")))
```

# WBT data

```{r}
  wbt_data <- 
    wbt_data %>%
    dplyr::mutate(stove = 
                    stove %>%
                    forcats::fct_recode("Rocket elbow" = "envirofit g3300",
                                        "Rocket elbow" = "gypa",
                                        "Ceramic plancha" = "onil",
                                        "Ceramic plancha" = "patsari",
                                        "Rocket elbow" = "stovetec greenfire",
                                        "Rocket elbow" = "improved no chimney",
                                        "Metal jiko" = "metal charcoal",
                                        "Ceramic jiko" = "ceramic charcoal",
                                        "Ceramic jiko" = "kcj standard",
                                        "Forced-draft gasifier" = "philips fan",
                                        "Three-stone fire" = "traditional",
                                        "Three-stone fire" = "three stone fire",
                                        "Rocket elbow" = "improved no chimney",
                                        "Forced-draft gasifier" = "gasifier",
                                        "Metal plancha" = "ecostufa"),
                  fuel = 
                    fuel %>%
                    forcats::fct_recode("Red oak (milled)" = "red oak",
                                        "Douglas fir (milled)" = "douglas fir",
                                        "Hardwood (lumps)" = "lump hardwood",
                                        "Coconut (briquettes)" = "coconut charcoal",
                                        "White oak (unknown)" = "white oak")) %>%
    dplyr::mutate(fst_type = NA,
                  fst_type = ifelse(grepl("Hardwood", fuel),
                                    "batch-fed\ncharcoal protocol", fst_type),
                  fst_type = ifelse(grepl("^wood$|Douglas fir|Red oak|White oak", fuel),
                                    "continuous-feed\nwood protocol", fst_type),
                  fst_type = ifelse(grepl("gasifier",stove), "batch-fed\nwood protocol", fst_type),
                  fst_type = as.factor(fst_type),
                  fst_type = fct_relevel(fst_type,
                                          "continuous-feed\nwood protocol",
                                          "batch-fed\ncharcoal protocol",
                                          "batch-fed\nwood protocol"),
                  test_type = "WBT")
```

# Field data

```{r}
  field_data <- 
    field_data %>%
    dplyr::mutate(stove = gsub(".*estufa.*", "Metal plancha", stove),
                  stove = gsub("three stone fire", "Three-stone fire", stove),
                  stove = gsub("rocket elbow", "Rocket elbow", stove),
                  stove = gsub(".*eco_h.*", "Metal plancha", stove),
                  stove = gsub(".*justa.*", "Ceramic plancha", stove),
                  stove = gsub("^traditional$", "Ceramic plancha", stove),
                  stove = gsub(".*philips.*", "Forced-draft gasifier", stove),
                  stove = gsub(".*ace.*", "Forced-draft gasifier", stove),
                  fuel = gsub(".charcoal.*", "Hardwood (lumps)", fuel),
                  fuel = gsub(".*wood.*", "Wood (collected)", fuel)) %>%
    dplyr::mutate(test_type = "Field")
```

```{r}
  rose_data <-
    rose_data %>%
    dplyr::filter(grepl("justa|ceramic|UGA|traditional|rocket elbow", stove),
                  stove != "ceramic rocket") %>%
    dplyr::mutate(stove = ifelse(grepl("ceramic|UGA", stove), "Ceramic jiko", stove),
                  stove = gsub("rocket elbow", "Rocket elbow", stove),
                  stove = gsub(".*justa.*", "Ceramic plancha", stove),
                  stove = gsub(".*traditional.*", "Ceramic plancha", stove),
                  fuel = gsub(".*hardwood.*", "Hardwood (lumps)", fuel),
                  fuel = gsub(".*wood.*", "Wood (collected)", fuel),
                  fuel = ifelse(field_site == "uganda", "Hardwood (lumps)", fuel)) %>%
    dplyr::mutate(test_type = "Field") %>%
    dplyr::select(-notes)
```

```{r}
  saveRDS(wbt_data, "../r_files/wbt_data_merged.RDS")
  saveRDS(field_data, "../r_files/field_data_merged.RDS")
  saveRDS(samples, "../r_files/lab_samples.RDS")
  saveRDS(rose_data, "../r_files/rose_data_merged.RDS")
```

