---
title: "Figures for Firepower Sweep Paper"
output:
  html_document:
    toc: true
    toc_float: true
    theme: paper
---

```{r load_libraries, echo=FALSE, message=FALSE}
  library(tidyverse)
  library(RColorBrewer)
  library(ggConvexHull)
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', warning=FALSE, message=FALSE, cache=FALSE, echo=FALSE)
```

```{r load_data}
  grav <- readRDS("../r_files/lab_grav_merged.RDS")
  wbt <- readRDS("../r_files/wbt_data_merged.RDS")
```

```{r}
  grav <-
    grav %>%
    dplyr::filter(id != "3B", fuel != "okote")
```

```{r}
  wbt_plot <-
    wbt %>%
    dplyr::filter(grepl("firepower", pol)) %>%
    dplyr::mutate(value = ifelse(units == "watts", value / 1000, value)) %>%
    tidyr::spread(var, value) %>%
    dplyr::mutate(fp_min = mean - stdev, fp_max = mean + stdev) %>%
    dplyr::rename("firepower" = "mean") %>%
    dplyr::select(-stdev, -pol, -units) %>%
    dplyr::left_join(wbt %>%
                     dplyr::select(id, stove, fuel, pol, var, value, fuel_notes, protocol, protocol_notes) %>%
                     dplyr::filter(grepl("mce", pol)) %>%
                     tidyr::spread(var, value) %>%
                     dplyr::mutate(mce_min = mean - stdev, mce_max = mean + stdev) %>%
                     dplyr::rename("mce" = "mean") %>%
                     dplyr::select(-stdev, -pol),
                     by = c("id", "protocol", "stove", "fuel", "fuel_notes", "protocol_notes")) %>%
    dplyr::filter(fuel_notes == "dry", grepl("three|metal jiko|rocket|forced|chimney|ceramic jiko", stove))
```

```{r fig_2a, fig.height=5, fig.width=13}
  wbt_cont <-
    wbt_plot %>%
    dplyr::filter(grepl("continuous", fst_type))

  wbt_cont2 <- 
    wbt_cont %>%
    tidyr::gather("fp_metric", "fp", 12:14) %>%
    tidyr::gather("mce_metric", "mce", 12:14)

  grav %>%
    dplyr::filter(grepl("fp|mce", var), grepl("three|rocket|chimney", stove),
                  grepl("continuous", fst_type)) %>%
    dplyr::select(-units) %>%
    tidyr::spread(var, val) %>%
    ggplot(aes(x = fp, y = mce, color = fuel)) +
      geom_point(size = 3) +
      geom_convexhull(aes(fill = fuel), alpha = 0.0, lwd = 1.5) + 
      geom_errorbarh(data = wbt_cont,
                     aes(x = firepower, y = mce, xmax = fp_max, xmin = fp_min), height = 0, size = 1) +
      geom_errorbar(data = wbt_cont,
                    aes(x = firepower, y = mce, ymin = mce_min, ymax = mce_max), width = 0, size = 1) +
      geom_point(data = wbt_cont, aes(x = firepower, y = mce, color = fuel), size = 3) +
      geom_convexhull(data = wbt_cont2, aes(x = fp, y = mce, fill = fuel), lwd = 1.5, alpha = 0.2, stroke = 3) + 
      scale_colour_manual(values = c("mediumpurple", "orange", "seagreen", "gold"),
                          guide = guide_legend(override.aes = list(size = 3, linetype = 0, fill = NA))) +
      scale_fill_manual(values = c("mediumpurple", "orange", "seagreen", "gold"),
                        guide = FALSE) +
      theme_bw() + 
      theme(text = element_text(size = 20),
            plot.title = element_text(hjust = 0.5),
            legend.position = "top") +
      facet_wrap(~stove, nrow = 1) +
      ggtitle("continuous-feed wood stoves") +
      scale_x_continuous(name="firepower (kW)", limits=c(0, 15)) +
      scale_y_continuous(name="combustion efficiency", limits=c(0.85, 1.0)) +
      labs(color = "fuel species")
```

```{r fig_2b, fig.height=5, fig.width=10}
  wbt_batch <-
    wbt_plot %>%
    dplyr::filter(grepl("batch", fst_type))

  wbt_batch2 <- 
    wbt_batch %>%
    tidyr::gather("fp_metric", "fp", 12:14) %>%
    tidyr::gather("mce_metric", "mce", 12:14)

  grav %>%
    dplyr::filter(grepl("fp|mce", var), grepl("ceramic jiko|^metal jiko$|forced", stove),
                  grepl("batch", fst_type)) %>%
    dplyr::select(-units) %>%
    tidyr::spread(var, val) %>%
    ggplot(aes(x = fp, y = mce, color = fuel)) +
      geom_point(size = 3) +
      geom_convexhull(alpha = 0.0, lwd = 1.5, aes(fill = fuel)) + 
      geom_errorbarh(data = wbt_batch,
                    aes(x = firepower, y = mce, xmax = fp_max, xmin = fp_min,
                        color = fuel), height = 0.00, shape = 1) +
      geom_errorbar(data = wbt_batch,
                    aes(x = firepower, y = mce, ymin = mce_min, ymax = mce_max,
                        color = fuel), width = 0.0, size = 1) +
      geom_point(data = wbt_batch, aes(x = firepower, y = mce, colour = fuel), size = 3) +
      geom_convexhull(data = wbt_batch2, aes(x = fp, y = mce, fill = fuel), alpha = 0.2, lwd = 1.5) + 
      scale_colour_manual(values = c("tomato", "gray40", "dodgerblue", "seagreen"),
                          guide = guide_legend(override.aes = list(size = 3, linetype = 0, fill = NA))) +
      scale_fill_manual(values = c("tomato", "gray40","dodgerblue", "seagreen"),
                          guide = FALSE) +
      theme_bw() + 
      theme(text = element_text(size = 18),
            plot.title = element_text(hjust = 0.5),
            legend.position = "top") +
      facet_wrap(~stove, nrow = 1) +
      ggtitle("batch-fed stoves") +
      scale_x_continuous(name="firepower (kW)", limits = c(0, 6)) +
      scale_y_continuous(name="combustion efficiency", limits = c(0.75, 1.0)) +
      labs(color = "fuel species")
```

```{r fig2c_SI, fig.height=5, fig.width=13}
  grav %>%
    dplyr::filter(grepl("fp|mce", var), grepl("imp. metal jiko|sunken|grill|mud", stove)) %>%
    dplyr::select(-units) %>%
    tidyr::spread(var, val) %>%
    ggplot(aes(x = fp, y = mce, color = fuel)) +
      geom_point(size = 3) +
      geom_convexhull(alpha = 0.0, lwd = 1.5, aes(fill = fuel)) + 
      scale_colour_manual(values = c("tomato", "mediumpurple", "orange"),
                          guide = guide_legend(override.aes = list(size = 3, linetype = 0, fill = NA))) +
      scale_fill_manual(values = c("tomato", "mediumpurple", "orange"),
                        guide = FALSE) +
      theme_bw() + 
      theme(text = element_text(size = 18),
            plot.title = element_text(hjust = 0.5),
            legend.position = "top") +
      facet_wrap(~stove, nrow = 1) +
      scale_x_continuous(name="firepower (kW)", limits = c(0, 6)) +
      scale_y_continuous(name="combustion efficiency", limits = c(0.75, 1.0)) +
      labs(color = "fuel species")
```