---
title: "Figure for Firepower Sweep Paper SI"
output:
  html_document:
    toc: true
    toc_float: true
    theme: paper
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, patchwork, openair, highfrequency, lubridate)
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', warning=FALSE, message=FALSE, cache=FALSE, echo=FALSE)
```

```{r load_data}
  wbt <- readRDS("../r_files/berkeley_wbt_data.RDS")
  fst <- readRDS("../r_files/firepower_sweep.RDS")
```

```{r}
  wbt <-
    wbt %>%
    dplyr::filter(mce != 1, !is.na(mce)) %>%
    dplyr::mutate(datetime = as.POSIXct(paste(date, time), format = "%m/%d/%Y %H:%M:%S")) %>%
    dplyr::select(test, stove, fuel, phase, date, datetime, mce)
```

```{r}
  fst <-
    fst %>%
    dplyr::filter(mce != 1, !is.na(mce)) %>%
    dplyr::mutate(datetime = as.POSIXct(paste(date, time), format = "%m/%d/%Y %H:%M:%S"))
```

```{r}
  fst_avg <-
    fst %>%
    dplyr::mutate(hours = hour(datetime),
                  minutes = minute(datetime)) %>%
    dplyr::group_by(date, hours, minutes, test, stove, fuel) %>%
    dplyr::summarise(mce_avg = mean(mce, na.rm = TRUE),
                     datetime = first(datetime)) %>%
    dplyr::mutate(test_type = "FST")
```

```{r}
  wbt_avg <-
    wbt %>%
    dplyr::mutate(hours = hour(datetime),
                  minutes = minute(datetime)) %>%
    dplyr::group_by(date, hours, minutes, test, stove, fuel, phase) %>%
    dplyr::summarise(mce_avg = mean(mce, na.rm = TRUE),
                     datetime = first(datetime)) %>%
    dplyr::mutate(test_type = "WBT")
```

```{r}
  fst_avg %>%
    dplyr::bind_rows(wbt_avg) %>%
    ggplot(aes(x = test_type, y = mce_avg)) +
      geom_boxplot(outlier.shape = NA) +
      geom_jitter(shape = 1, width = 0.25) +
      ylim(0.8, 1) +
      theme_bw() +
      theme(text = element_text(size = 16)) +
      facet_wrap(~stove) +
      ylab("one-minute averaged MCE") +
      xlab("")
```

