---
title: "Figures for Firepower Sweep Paper"
output:
  html_document:
    toc: true
    toc_float: true
    theme: paper
---

```{r load_libraries, echo=FALSE, message=FALSE}
  library(tidyverse)
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', warning=FALSE, message=FALSE, cache=FALSE, echo=FALSE)
```

```{r load_data}
  grav <- readRDS("../r_files/lab_grav_merged.RDS")
  jetter_data <- readRDS("../r_files/jetter_merged.RDS")
  roden_data <- readRDS("../r_files/roden_data.RDS")
  rose_data <- readRDS("../r_files/rose_field_data.RDS")
```

```{r}
  grav <-
    grav %>%
    dplyr::filter(id != "3B", fuel != "okote")
```

```{r}
  jetter_plot <-
    jetter_data %>%
    dplyr::filter(grepl("firepower", pol)) %>%
    dplyr::mutate(value = value / 1000) %>%
    tidyr::spread(var, value) %>%
    dplyr::mutate(fp_min = mean - stdev, fp_max = mean + stdev) %>%
    dplyr::rename("firepower" = "mean") %>%
    dplyr::select(-stdev, -pol, -units) %>%
    dplyr::left_join(jetter_data %>%
                     dplyr::select(stove, fuel, pol, var, value, fuel_notes, protocol, protocol_notes) %>%
                     dplyr::filter(grepl("mce", pol)) %>%
                     tidyr::spread(var, value) %>%
                     dplyr::mutate(mce_min = mean - stdev, mce_max = mean + stdev) %>%
                     dplyr::rename("mce" = "mean") %>%
                     dplyr::select(-stdev, -pol),
                     by = c("protocol", "stove", "fuel", "fuel_notes", "protocol_notes")) %>%
    dplyr::left_join(jetter_data %>%
                     dplyr::filter(pol == "pm2.5", units == "grams per kilogram") %>%
                     dplyr::select(stove, fuel, pol, var, value, fuel_notes, protocol, protocol_notes) %>%
                     tidyr::spread(var, value) %>%
                     dplyr::mutate(pm_min = mean - stdev, pm_max = mean + stdev) %>%
                     dplyr::rename("pm2.5" = "mean") %>%
                     dplyr::select(-stdev, -pol),
                     by = c("protocol", "stove", "fuel", "fuel_notes", "protocol_notes")) %>%
    dplyr::left_join(jetter_data %>%
                     dplyr::filter(pol == "co", units == "grams per kilogram") %>%
                     dplyr::select(stove, fuel, pol, var, value, fuel_notes, protocol, protocol_notes) %>%
                     tidyr::spread(var, value) %>%
                     dplyr::mutate(co_min = mean - stdev, co_max = mean + stdev) %>%
                     dplyr::rename("co" = "mean") %>%
                     dplyr::select(-stdev, -pol),
                     by = c("protocol", "stove", "fuel", "fuel_notes", "protocol_notes")) %>%
    dplyr::filter(grepl("three|gasifier|justa|charcoal [:(:]|rocket", stove),
                  fuel_notes == "dry") %>%
    dplyr::mutate(stove = gsub("[:(:]small[:):].*", "(small)", stove))
```

```{r}
  roden_plot <-
    roden_data %>%
    dplyr::filter(grepl("pm", pol)) %>%
    tidyr::spread(var, value) %>%
    dplyr::mutate(pm_min = mean - stdev, pm_max = mean + stdev) %>%
    dplyr::rename("pm_mean" = "mean") %>%
    dplyr::select(-stdev, -pol, -units, -ref) %>%
    dplyr::left_join(roden_data %>%
                     dplyr::select(id, pol, var, value) %>%
                     dplyr::filter(grepl("co", pol)) %>%
                     tidyr::spread(var, value) %>%
                     dplyr::mutate(co_min = mean - stdev, co_max = mean + stdev) %>%
                     dplyr::rename("co_mean" = "mean") %>%
                     dplyr::select(-stdev, -pol),
                     by = c("id")) %>%
    dplyr::left_join(roden_data %>%
                     dplyr::filter(pol == "ec") %>%
                     dplyr::select(id, pol, var, value) %>%
                     tidyr::spread(var, value) %>%
                     dplyr::mutate(ec_min = mean - stdev, ec_max = mean + stdev) %>%
                     dplyr::rename("ec_mean" = "mean") %>%
                     dplyr::select(-stdev, -pol),
                     by = c("id")) %>%
    dplyr::left_join(roden_data %>%
                     dplyr::filter(pol == "oc") %>%
                     dplyr::select(id, pol, var, value) %>%
                     tidyr::spread(var, value) %>%
                     dplyr::mutate(oc_min = mean - stdev, oc_max = mean + stdev) %>%
                     dplyr::rename("oc_mean" = "mean") %>%
                     dplyr::select(-stdev, -pol),
                     by = c("id"))
```

```{r fig_2, fig.height=8, , fig.width=10}
  grav %>%
    dplyr::filter(grepl("fp|mce", var), grepl("ceramic|philips|justa [:(:]art|metal charcoal [:(:]small|elbow [:(:]envirofit|three", stove)) %>%
    dplyr::select(-units) %>%
    tidyr::spread(var, val) %>%
    ggplot(aes(x = fp, y = mce)) +
      geom_point(aes(color = fuel), shape = 4, size = 3, stroke = 1) +
      geom_point(data = jetter_plot,
                 aes(x = firepower, y = mce, shape = protocol, color = fuel),
                 size = 3, stroke = 1) +
      geom_errorbarh(data = jetter_plot,
                     aes(x = firepower, y = mce, xmax = fp_max, xmin = fp_min, color = fuel), height = 0.02) +
      geom_errorbar(data = jetter_plot,
                    aes(x = firepower, y = mce, ymin = mce_min, ymax = mce_max, color = fuel), width = 0.5) +
      theme_bw() + 
      theme(text = element_text(size=16),
            legend.position = "right") +
      facet_wrap(~stove) +
      ylab("Modified Combustion Efficiency") +
      labs(shape = "WBT phase", color = "fuel species") +
      xlab("Firepower (kW)")
```

```{r SI_XX_1, fig.height=8, , fig.width=10}
  grav %>%
    dplyr::filter(grepl("fp|mce", var), !grepl("ceramic|philips|justa [:(:]art|metal charcoal [:(:]small|elbow [:(:]envirofit|three", stove)) %>%
    dplyr::select(-units) %>%
    tidyr::spread(var, val) %>%
    ggplot(aes(x = fp, y = mce)) +
      geom_point(aes(color = fuel), shape = 4, size = 3, stroke = 1) +
      theme_bw() + 
      theme(text = element_text(size=16),
            legend.position = "right") +
      facet_wrap(~stove) +
      ylab("Modified Combustion Efficiency") +
      labs(shape = "WBT phase", color = "fuel species") +
      xlab("Firepower (kW)")
```

```{r fig_SI_XX-2, fig.height=10, , fig.width=14}
  grav %>%
    dplyr::filter(grepl("co_ef|pm_ef", var)) %>%
    dplyr::select(-units) %>%
    tidyr::spread(var, val) %>%
    ggplot(aes(x = pm_ef, y = co_ef)) +
      geom_point(aes(color = fuel), shape = 4, size = 3, stroke = 1) +
      geom_point(data = jetter_plot,
                 aes(x = pm2.5, y = co, shape = protocol, color = fuel),
                 size = 3, stroke = 1) +
      geom_errorbarh(data = jetter_plot,
                     aes(x = pm2.5, y = co, xmax = pm_max, xmin = pm_min, color = fuel), height = 0.02) +
      geom_errorbar(data = jetter_plot,
                    aes(x = pm2.5, y = co, ymin = co_min, ymax = co_max, color = fuel), width = 0.5) +
      theme_bw() + 
      theme(text = element_text(size=16),
            legend.position = "right") +
      facet_wrap(~stove, scales = "free") +
      ylab("Carbon Monoxide Emissions Factor (g/kg fuel)") +
      labs(shape = "WBT phase", color = "fuel species") +
      xlab("Particulate Matter Emissions Factor (g/kg fuel)")
```

```{r}
  field_plot <-
    grav %>%
    dplyr::filter(grepl("co_ef|pm_ef|bc_ef", var),
                  grepl("three|justa|rocket|clay ring|charcoal [:(:]small[:):]", stove)) %>%
    dplyr::mutate(stove = gsub(" [:(:]small[:):]", "", stove)) %>%
    dplyr::mutate(stove = gsub("clay ring", "mud chula", stove)) %>%
    dplyr::mutate(stove = gsub("rocket .*", "rocket elbow", stove)) %>%
    dplyr::mutate(stove = gsub(".*artisan.*", "justa", stove)) %>%
    dplyr::mutate(stove = gsub(".*envirofit.*", "improved plancha", stove)) %>%
    dplyr::mutate(fuel = gsub(".*doug.*", "douglas fir (milled)", fuel)) %>%
    dplyr::mutate(fuel = gsub(".*euc.*", "eucalyptus (split)", fuel)) %>%
    tidyr::spread(var, val) %>%
    dplyr::select(stove, fuel, co_ef, pm_ef, bc_ef, sample_id) %>%
    dplyr::mutate("phase" = sample_id) %>%
    dplyr::filter(!is.na(pm_ef)) %>%
    dplyr::mutate(protocol = "FST")

  field_plot_2 <-
    jetter_data %>%
    dplyr::filter(grepl("co|pm", pol),
                  grepl("mean", var),
                  grepl("three|rocket|onil|greenfire|charcoal [:(:]small[:):]", stove)) %>%
    dplyr::mutate(stove = gsub("rocket .*", "rocket elbow", stove)) %>%
    dplyr::mutate(stove = gsub(".*green.*", "rocket elbow", stove)) %>%
    dplyr::mutate(stove = gsub(".*onil.*", "improved plancha", stove)) %>%
    dplyr::mutate(fuel = "red oak (milled)") %>%
    tidyr::spread(pol, value) %>%
    dplyr::mutate(stove = gsub(" [:(:]small[:):].*", "", stove)) %>%
    dplyr::rename("co_ef" = "co", "pm_ef" = "pm2.5") %>%
    dplyr::select(stove, fuel, co_ef, pm_ef, protocol) %>%
    dplyr::mutate("phase" = protocol) %>%
    dplyr::mutate(protocol = "WBT")
  
  field_plot_3 <-
    roden_data %>%
    dplyr::select(id, stove, fuel, pol, var, value) %>%
    dplyr::filter(grepl("co|pm|ec", pol), grepl("mean", var), grepl("justa|eco_h|estufa", stove)) %>%
    dplyr::mutate(stove = gsub(".*estufa.*", "improved plancha", stove)) %>%
    dplyr::mutate(stove = gsub(".*eco_h.*", "improved plancha", stove)) %>%
    tidyr::spread(pol, value) %>%
    dplyr::rename("co_ef" = "co", "pm_ef" = "pm", "bc_ef" = "ec") %>%
    dplyr::mutate(fuel = "unkown wood species (collected)") %>%
    dplyr::select(stove, fuel, co_ef, pm_ef) %>%
    dplyr::mutate(protocol = "Honduras*")
  
  field_plot_4 <-
    rose_data %>%
    dplyr::filter(grepl("rocket elbow|justa|mud|[:(:]small[:):]", stove)) %>%
    dplyr::rename("protocol" = "field_site") %>%
    dplyr::mutate(stove = gsub(" [:(:]small[:):]", "", stove)) %>%
    dplyr::mutate(protocol = gsub("hon.*", "Honduras", protocol)) %>%
    dplyr::mutate(protocol = gsub("india.*", "India", protocol)) %>%
    dplyr::mutate(protocol = gsub("uga.*", "Uganda", protocol))
    
  field_plot <-
    dplyr::bind_rows(field_plot, field_plot_2) %>%
    dplyr::bind_rows(field_plot_3) %>%
    dplyr::bind_rows(field_plot_4)
```

```{r fig_4_1, fig.height=8, , fig.width=10}
  ggplot(field_plot, aes(x = pm_ef, y = co_ef)) +
    geom_point(aes(color = protocol, shape = stove), size = 3, stroke = 1) +
    scale_shape(aes(fill = FALSE)) +
    theme_bw() + 
    theme(text = element_text(size=16),
          legend.position = "right") +
    scale_x_log10() +
    scale_y_log10() +
    ylab("Carbon Monoxide Emissions Factor (g/kg fuel)") +
    labs(shape = "protocol", color = "stove category") +
    xlab("Particulate Matter Emissions Factor (g/kg fuel)")
```


```{r, fig.height=4, fig.width=13}
  field_plot %>%
  dplyr::filter(!is.na(co_ef)) %>%
  ggplot(aes(y = co_ef, x = protocol)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(aes(color = fuel), width = 0.15, shape = 4, stroke = 1) +
    theme_bw() + 
    scale_y_log10() +
    theme(text = element_text(size = 14),
          axis.text.x = element_text(angle = 25, hjust = 1, vjust = 1, size = 10),
          legend.position = "top") +
    facet_grid(~stove, space = "free_x", scale = "free_x") +
    ylab("Carbon Monoxide (g/kg fuel)") +
    xlab("")
```

```{r, fig.height=4, fig.width=13}
  field_plot %>%
  dplyr::filter(!is.na(pm_ef)) %>%
  ggplot(aes(y = pm_ef, x = protocol)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(aes(color = fuel), width = 0.15, shape = 4, stroke = 1) +
    theme_bw() + 
    scale_y_log10() +
    theme(text = element_text(size = 14),
          axis.text.x = element_text(angle = 25, hjust = 1, vjust = 1, size = 10),
          legend.position = "top") +
    facet_grid(~stove, space = "free_x", scale = "free_x") +
    ylab("Particulate Matter (g/kg fuel)") +
    xlab("")
```

```{r, fig.height=4, fig.width=10}
  field_plot %>%
  dplyr::filter(!is.na(bc_ef), !grepl("charcoal",stove)) %>%
  ggplot(aes(y = bc_ef, x = protocol)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(aes(color = fuel), width = 0.15, shape = 4, stroke = 1) +
    theme_bw() + 
    scale_y_log10() +
    theme(text = element_text(size = 14),
          axis.text.x = element_text(angle = 25, hjust = 1, vjust = 1, size = 10),
          legend.position = "top") +
    facet_grid(~stove, space = "free_x", scale = "free_x") +
    ylab("Black Carbon (g/kg fuel)") +
    xlab("")
```

```{r, fig.height=4, fig.width=13}
  field_plot %>%
  dplyr::filter(!is.na(co_ef)) %>%
  ggplot(aes(y = co_ef, x = protocol)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(aes(color = phase), width = 0.15, shape = 4, stroke = 1) +
    theme_bw() + 
    scale_y_log10() +
    theme(text = element_text(size = 14),
          axis.text.x = element_text(angle = 25, hjust = 1, vjust = 1, size = 10),
          legend.position = "top") +
    facet_grid(~stove, space = "free_x", scale = "free_x") +
    ylab("Carbon Monoxide (g/kg fuel)") +
    xlab("")
```

```{r, fig.height=4, fig.width=13}
  field_plot %>%
  dplyr::filter(!is.na(pm_ef)) %>%
  ggplot(aes(y = pm_ef, x = protocol)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(aes(color = phase), width = 0.15, shape = 4, stroke = 1) +
    theme_bw() + 
    scale_y_log10() +
    theme(text = element_text(size = 14),
          axis.text.x = element_text(angle = 25, hjust = 1, vjust = 1, size = 10),
          legend.position = "top") +
    facet_grid(~stove, space = "free_x", scale = "free_x") +
    ylab("Particulate Matter (g/kg fuel)") +
    xlab("")
```

```{r, fig.height=4, fig.width=10}
  field_plot %>%
  dplyr::filter(!is.na(bc_ef), !grepl("charcoal",stove)) %>%
  ggplot(aes(y = bc_ef, x = protocol)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(aes(color = phase), width = 0.15, shape = 4, stroke = 1) +
    theme_bw() + 
    scale_y_log10() +
    theme(text = element_text(size = 14),
          axis.text.x = element_text(angle = 25, hjust = 1, vjust = 1, size = 10),
          legend.position = "top") +
    facet_grid(~stove, space = "free_x", scale = "free_x") +
    ylab("Black Carbon (g/kg fuel)") +
    xlab("")
```