---
output:
  pdf_document:
    toc: no
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, patchwork, knitr, kableExtra)
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', warning=FALSE, message=FALSE, cache=FALSE, echo=FALSE)
```

```{r load_data}
  grav <- readRDS("../r_files/lab_grav_merged.RDS")
  grav_flags <- readRDS("../r_files/grav_flags.RDS")
```

```{r}
  # energy_ef <-
  #   grav %>%
  #   dplyr::filter(var == "pm_mass") %>%
  #   tidyr::spread(var, val) %>%
  #   dplyr::left_join(dplyr::select(energy, -units), by = c("id" = "test_id", "sample_id")) %>%
  #   dplyr::mutate(energy_ef = pm_mass / (energy_delivered / 1e6)) %>%
  #   dplyr::select(stove, fuel, id, sample_id, energy_ef)
```

```{r}
  time_ef <-
    grav %>%
    dplyr::filter(grepl("pm_rate|co_rate", var)) %>%
    tidyr::spread(var, val) %>%
    dplyr::select(id, sample_id, pm_rate, co_rate) %>%
    dplyr::mutate(pm_rate = format(round(pm_rate, 2), nsmall = 2),
                  co_rate = format(round(co_rate, 2), nsmall = 2),
                  pm_rate = as.character(pm_rate),
                  co_rate = as.character(co_rate)) %>%
    dplyr::left_join(grav_flags, by = c("id", "sample_id")) %>%
    dplyr::mutate(pm_rate = ifelse(pm_flag == 1, paste0(pm_rate, "*"), pm_rate),
                  pm_rate = ifelse(pm_flag == 2, paste0(pm_rate, "**"), pm_rate),
                  pm_rate = ifelse(bb_pm_flag == 1, "BB", pm_rate),
                  pm_rate = gsub("NA.*", "NA", pm_rate)) %>%
    dplyr::select(-bc_flag, -pm_flag, -bb_bc_flag, -bb_pm_flag) %>%
    dplyr::mutate(sample_id = gsub("start_up", "start-up", sample_id),
                  sample_id = gsub("shutdown", "shut-down", sample_id),
                  sample_id = gsub("fp_", "", sample_id))
```

```{r}
  fuel_mass_ef <- 
    grav %>%
    dplyr::select(stove, fuel, id, sample_id, var, val) %>%
    dplyr::filter(grepl("fp|mce|pm_ef|co_ef", var)) %>%
    tidyr::spread(var, val) %>%
    dplyr::select(stove, fuel, id, sample_id, fp, mce, pm_ef, co_ef) %>%
    dplyr::mutate(stove = as.character(stove),
                  stove = ifelse(grepl("^4[A-Z]", id), "ceramic plancha (mod 1)", stove),
                  stove = ifelse(grepl("^5[A-Z]", id), "ceramic plancha (mod 2)", stove),
                  stove = ifelse(grepl("^8[A-Z]|^9[A-Z]", id), "ceramic jiko (sm.)", stove),
                  stove = ifelse(grepl("^10[A-Z]|^11[A-Z]", id), "ceramic jiko (lg.)", stove),
                  stove = ifelse(grepl("^12[A-Z]", id), "metal jiko (lg.)", stove),
                  stove = ifelse(grepl("^13[A-Z]", id), "metal jiko (lg.)", stove),
                  stove = ifelse(grepl("^14[A-Z]|^29[A-Z]", id), "imp. metal jiko", stove),
                  stove = ifelse(grepl("^19[A-Z]|^20[A-Z]", id), "rocket elbow (mod 1)", stove),
                  stove = ifelse(grepl("^21[A-Z]", id), "rocket elbow (mod 2)", stove),
                  stove = ifelse(grepl("^21[A-Z]", id), "rocket elbow (mod 2)", stove),
                  stove = ifelse(grepl("^22[A-Z]|^24[A-Z]", id),
                                 "forced-draft gasifier (mod 2)", stove),
                  stove = ifelse(grepl("^23[A-Z]", id), "forced-draft gasifier (mod 1)", stove)) %>%
    dplyr::mutate(fp = format(round(fp, 2), nsmall = 2),
                  mce = format(round(mce, 2), nsmall = 2),
                  pm_ef = format(round(pm_ef, 2), nsmall = 2),
                  co_ef = format(round(co_ef, 2), nsmall = 2),
                  fp = as.character(fp),
                  mce = as.character(mce),
                  pm_ef = as.character(pm_ef),
                  co_ef = as.character(co_ef)) %>%
    dplyr::left_join(grav_flags, by = c("id", "sample_id")) %>%
    dplyr::mutate(pm_ef = ifelse(pm_flag == 1, paste0(pm_ef, "*"), pm_ef),
                  pm_ef = ifelse(pm_flag == 2, paste0(pm_ef, "**"), pm_ef),
                  pm_ef = ifelse(bb_pm_flag == 1, "BB", pm_ef),
                  pm_ef = gsub("NA.*", "NA", pm_ef)) %>%
    dplyr::select(-bc_flag, -pm_flag, -bb_bc_flag, -bb_pm_flag) %>%
    dplyr::mutate(sample_id = gsub("start_up", "start-up", sample_id),
                  sample_id = gsub("shutdown", "shut-down", sample_id),
                  sample_id = gsub("fp_", "", sample_id))
```

```{r}
  emissions <-
    time_ef %>%
    dplyr::left_join(fuel_mass_ef , by = c("id", "sample_id")) %>%
    dplyr::mutate(id =
                    id %>%
                    as_factor) %>%
    dplyr::filter(fuel != "okote") %>%
    dplyr::arrange(id) %>%
    dplyr::select(stove, fuel, id, sample_id, fp, mce, pm_ef, co_ef, pm_rate, co_rate) %>%
    dplyr::rename("MCE" = "mce",
                  "Firepower" = "fp",
                  "PM$_{2.5}$  EF" = "pm_ef",
                  "CO EF" = "co_ef",
                  "segment" = "sample_id",
                  "PM$_{2.5}$ Rate" = "pm_rate",
                  "CO Rate" = "co_rate")
```

```{r}
  emissions %>%
    dplyr::arrange(id) %>%
    kable(escape = FALSE, booktabs = TRUE, align = "c",
          longtable = TRUE) %>%
    kable_styling(position = "left", font_size = 6.5,
                  latex_options = "repeat_header") %>%
    add_header_above(c(" " = 6, "g/kg-fuel" = 2, "mg/min" = 2)) %>%
    footnote(general = "BB is below background; MCE is modified combustion efficiency; * indicates a value below limit of detection; ** indicates a value below limit of quantification", threeparttable = TRUE)
```
