---
title: "Build firepower model"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  library(tidyverse)
  library(lme4)
  library(broom)
  library(psych)
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', warning=FALSE, message=FALSE, cache=FALSE)
```

```{r, echo=FALSE}
  grav <- readRDS("../r_files/lab_grav_merged.RDS")
```

# Organize data

```{r}
  pm_ef <-
    grav %>%
    dplyr::filter(id != "3B", fuel != "okote", grepl("pm_ef|fp|mce", var)) %>%
    dplyr::mutate("stove_fuel" = paste(stove, fuel)) %>%
    dplyr::select(id, date, sample_id, tester, var, val, test_type, stove_fuel, stove, fuel) %>%
    tidyr::spread(var, val) %>%
    dplyr::mutate(rep = gsub("*[0-9]", "", id)) %>%
    dplyr::mutate(stove_fuel = forcats::as_factor(stove_fuel),
                  rep = forcats::as_factor(rep),
                  date = forcats::as_factor(as.character(date)),
                  tester = forcats::as_factor(tester),
                  sample_id = forcats::as_factor(sample_id)) %>%
    dplyr::group_by(test_type)
```

# Describe data

```{r, echo=FALSE}
  describeBy(dplyr::select(pm_ef, fp, mce, pm_ef, test_type), group = "test_type")
```

```{r, echo=FALSE}
  pm_ef %>%
  tidyr::gather("var", "val", 9:11) %>%
  ggplot(aes(val)) +
    theme_bw() +
    geom_histogram() +
    facet_wrap(~var, scales = "free")
```

```{r, echo=FALSE}
  pm_ef %>%
  tidyr::gather("var", "val", 9:10) %>%
  ggplot(aes(x = val, y = pm_ef)) +
    geom_point(shape = 1) +
    theme_bw() +
    facet_wrap(var~test_type, scales = "free") +
    xlab("") +
    ylab("PM emissions")
```

# Fixed effects

Parameters of interest:

* stove/fuel combination
* firepower (firepower = burn rate*constant)
* combustion efficiency
* burn rate

```{r, echo=FALSE}
  pm_ef %>%
  tidyr::gather("var", "val", 9:10) %>%
  ggplot(aes(x = val, y = pm_ef, color = stove_fuel)) +
    geom_point(shape = 1) +
    geom_smooth(method = "lm", se = FALSE, alpha = 0.5) +
    theme_bw() +
    theme(legend.position = "none") +
    facet_wrap(var~test_type, ncol = 3, scales = "free") +
    ylab("PM Emissions Factor")
```

# Random (control?) effects

```{r, echo=FALSE, eval=FALSE}
  test <-
    pm_ef %>% 
      nest(-test_type) %>% 
      mutate(fit = map(data, ~ lm(pm_ef ~ sample_id + date + tester + rep, data = .)),
             results = map(fit, summary)) %>% 
      unnest(results)

    ggplot(pm_ef, aes(x = factor(test_type), y = r.squared)) +
      geom_bar(stat = "identity") +
      labs(x = "test type", y = expression(R^{2}))
```

* center all predictors on the mean

```{r}
  pm_ef <-
    pm_ef %>%
    dplyr::mutate(pm_ef = scale(pm_ef, center = TRUE),
                  fp = scale(fp, center = TRUE),
                  mce = scale(mce, center = TRUE))
```
