---
title: "Figure 4 for Firepower Sweep Paper"
output:
  html_document:
    toc: true
    toc_float: true
    theme: paper
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, patchwork)
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', warning=FALSE, message=FALSE, cache=FALSE, echo=FALSE)
```

```{r load_data}
  grav <- readRDS("../r_files/lab_grav_merged.RDS")
  wbt <- readRDS("../r_files/wbt_data_merged.RDS")
  field <- readRDS("../r_files/field_data_merged.RDS")
  rose <- readRDS("../r_files/rose_data_merged.RDS")
```

```{r}
  source("../r_scripts/functions.r")
```

```{r}
  grav <-
    grav %>%
    dplyr::filter(id != "3B", fuel != "okote")
```

```{r}
  continuous <- 
    grav %>%
    dplyr::filter(grepl("pm_ef|co_ef|bc_ef", var), grepl("continuous", fst_type), !is.na(val), val > 0) %>%
    dplyr::select(-units) %>%
    tidyr::spread(var, val) %>%
    dplyr::mutate(phase = as.character(sample_id),
                  phase = ifelse(grepl("start_up", sample_id), "FST: start-up", phase),
                  phase = ifelse(grepl("shutdown", sample_id), "FST: shut-down", phase),
                  phase = ifelse(grepl("1|2|3|4", sample_id), "FST: sweep-up", phase),
                  phase = ifelse(grepl("5|6|7", sample_id), "FST: sweep-down", phase),
                  phase = forcats::fct_relevel(phase,
                                               "FST: start-up",
                                                "FST: sweep-up",
                                                "FST: sweep-down",
                                                "FST: shut-down"),
                  stove = forcats::fct_relevel(stove,
                                               "Three-stone fire",
                                               "Mud chulha",
                                               "Metal grill",
                                               "Rocket elbow",
                                               "Ceramic plancha",
                                               "Metal plancha"))
```

```{r}
  batch <- 
    grav %>%
    dplyr::filter(grepl("pm_ef|co_ef|bc_ef", var), grepl("batch", fst_type), !is.na(val), val > 0) %>%
    dplyr::select(-units) %>%
    tidyr::spread(var, val) %>%
    dplyr::mutate(phase = as.character(sample_id),
                  phase = ifelse(grepl("start_up", sample_id), "FST: start-up", phase),
                  phase = ifelse(grepl("shutdown", sample_id), "FST: shut-down", phase),
                  phase = ifelse(grepl("3", sample_id), "FST: refuel", phase),
                  phase = ifelse(grepl("1|2", sample_id), "FST: pre-refuel", phase),
                  phase = ifelse(grepl("4|5", sample_id), "FST: post-refuel", phase)) %>%
  dplyr::mutate(stove = forcats::fct_relevel(stove,
                                             "Ceramic jiko",
                                             "Metal jiko",
                                             "Forced draft gasifier")) %>%
  dplyr::mutate(fuel = forcats::fct_relevel(fuel,
                                            "Coconut (briquettes)",
                                            "Hardwood (lumps)",
                                            "Eucalyptus (pellets)",
                                            "Red oak (milled)")) %>%
  dplyr::mutate(phase = forcats::fct_relevel(phase,
                                              "FST: start-up",
                                              "FST: pre-refuel",
                                              "FST: refuel",
                                              "FST: post-refuel",
                                              "FST: shut-down"))
```

```{r}
  plot_2 <-
    field %>%
    dplyr::filter(grepl("co|pm|ec", pol),
                  grepl("mean", var),
                  grepl("Ceramic plancha|Rocket elbow|Three-stone fire|draft", stove)) %>%
    tidyr::spread(pol, value) %>%
    dplyr::rename("co_ef" = "co", "pm_ef" = "pm", "bc_ef" = "ec") %>%
    dplyr::select(stove, fuel, co_ef, pm_ef, bc_ef) %>%
    dplyr::mutate(test_type = "Field")
```

```{r}
  plot_3 <-
    rose %>%
    dplyr::select(stove, fuel, co_ef, pm_ef, bc_ef) %>%
    dplyr::mutate(test_type = "Field")

  plot_4 <-
    wbt %>%
    dplyr::filter(grepl("pm|pm2.5", pol), grepl("grams per kilogram", units),
                  var == "mean", fuel_notes == "dry") %>%
    dplyr::select(id, stove, fuel, pol, var, value, protocol, protocol_notes, test_type) %>%
    tidyr::spread(var, value) %>%
    dplyr::rename("pm_ef" = "mean") %>%
    dplyr::left_join(wbt %>%
                     dplyr::filter(grepl("co", pol), grepl("grams per kilogram", units),
                     var == "mean", fuel_notes == "dry") %>%
                     dplyr::select(id, stove, fuel, pol, var, value, protocol, protocol_notes,
                                   test_type) %>%
                     tidyr::spread(var, value) %>%
                     dplyr::rename("co_ef" = "mean"),
                     by = c("id", "protocol", "stove", "fuel", "protocol_notes", "test_type")) %>%
    dplyr::filter(grepl("Three|Metal jiko|Rocket|Forced|plancha*|Ceramic jiko", stove)) %>%
    dplyr::mutate(test_type = "WBT") %>%
    dplyr::select(stove, fuel, co_ef, pm_ef, test_type)
```

```{r}
  plot <-
    continuous %>%
    dplyr::bind_rows(batch) %>%
    dplyr::mutate(test_type = "FST") %>%
    dplyr::bind_rows(plot_2) %>%
    dplyr::bind_rows(plot_3) %>%
    dplyr::bind_rows(plot_4) %>%
    dplyr::filter(grepl("Ceramic plancha|Three|Ceramic jiko|Forced|Rocket", stove)) %>%
    dplyr::mutate(fuel = forcats::fct_relevel(fuel,
                                              "Douglas fir (milled)",
                                              "Eucalyptus (split)",
                                              "Coconut (briquettes)",
                                              "Hardwood (lumps)",
                                              "Eucalyptus (pellets)",
                                              "Red oak (milled)"),
                  stove = forcats::fct_relevel(stove,
                                               "Three-stone fire",
                                               "Rocket elbow",
                                               "Ceramic plancha",
                                               "Ceramic jiko",
                                               "Forced-draft gasifier"))
```

```{r}
  pm_summary <-
  plot %>%
    dplyr::group_by(stove, test_type) %>%
    dplyr::summarise(min = min(pm_ef, na.rm = TRUE),
                     max = max(pm_ef, na.rm = TRUE),
                     median = median(pm_ef, na.rm = TRUE),
                     mean = mean(pm_ef, na.rm = TRUE),
                     stdev = sd(pm_ef, na.rm = TRUE)) %>%
    dplyr::mutate(range = max - min)
```

```{r}
  co_summary <-
  plot %>%
    dplyr::group_by(stove, test_type) %>%
    dplyr::summarise(min = min(co_ef, na.rm = TRUE),
                     max = max(co_ef, na.rm = TRUE),
                     median = median(co_ef, na.rm = TRUE),
                     mean = mean(co_ef, na.rm = TRUE),
                     stdev = sd(co_ef, na.rm = TRUE)) %>%
    dplyr::mutate(range = max - min)
```

# Plots

```{r fig_4a, fig.width=8, fig.height=3}
p1 <- 
  plot %>%
    ggplot(aes(x = test_type, y = pm_ef)) +
      geom_jitter(aes(color = fuel), shape = 1, size = 1.5, stroke = 1.5, width = 0.25) +
      #geom_errorbar(data = pm_summary,
      #              aes(x = test_type, y = mean, ymin = min, ymax = max),
      #              stroke = 1, width = 0.25) +
      scale_color_manual(values = c("#999999", "#E69F00",
                                    "yellowgreen", "darkcyan", "coral3", "#0072B2", "#7b3294")) +
      guides(color = guide_legend(override.aes = list(size = 1.5,
                                                      shape = 1, linetype = 0))) +
      scale_y_continuous(trans = "log10", limits = c(0.1, NA)) +
      theme_bw() +
      theme(text = element_text(size = 16),
            axis.title.y = element_text(size = 16),
            strip.text.x = element_text(size = 14),
            strip.background = element_rect(fill = "white"),
            plot.title = element_text(hjust = 0.5),
            legend.position = "top") +
        facet_wrap(~ stove, nrow = 1, scales = "free") +
        xlab("") +
        ylab(expression(paste(PM[2.5], " Emissions Factors (g/kg-fuel)"))) +
        labs(shape = "", color = "")
```

```{r fig_4b, fig.width=8, fig.height=3}
p2 <- 
  plot %>%
    ggplot(aes(x = test_type, y = co_ef)) +
      geom_jitter(aes(color = fuel), shape = 1, size = 1.5, stroke = 1.5, width = 0.25) +
      #geom_errorbar(data =  co_summary,
      #              aes(x = test_type, y = mean, ymin = min, ymax = max),
      #              stroke = 1, width = 0.25) +
      scale_color_manual(values = c("#999999", "#E69F00",
                                    "yellowgreen", "darkcyan", "coral3", "#0072B2", "#7b3294")) +
      guides(color = guide_legend(override.aes = list(size = 2,
                                                      shape = 1, linetype = 0))) +
      scale_y_continuous(limits = c(0, NA)) +
      theme_bw() +
      theme(text = element_text(size = 16),
            axis.title.y = element_text(size = 16),
            strip.text.x = element_text(size = 14),
            strip.background = element_rect(fill = "white"),
            plot.title = element_text(hjust = 0.5),
            legend.position = "none") +
        facet_wrap(~ stove, nrow = 1, scales = "free") +
        xlab("") +
        ylab("CO Emissions Factors (g/kg-fuel)") +
        labs(shape = "", color = "")
```

```{r figure_4, echo=FALSE, fig.width=12, fig.height=8, dpi=600, dev='pdf'}
  p1 + p2 + plot_layout(ncol = 1, heights = c(1, 1))
```

```{r fig_4a_2, fig.width=8, fig.height=3}
p1 <- 
  plot %>%
    ggplot(aes(x = test_type, y = pm_ef)) +
      geom_jitter(color = "#0072B2", shape = 1, size = 1.5, stroke = 1.5, width = 0.25) +
      #geom_errorbar(data = pm_summary,
      #              aes(x = test_type, y = mean, ymin = min, ymax = max),
      #              stroke = 1, width = 0.25) +
      scale_color_manual(values = c("#999999", "#E69F00",
                                    "yellowgreen", "darkcyan", "coral3", "#0072B2", "#7b3294")) +
      guides(color = guide_legend(override.aes = list(size = 1.5,
                                                      shape = 1, linetype = 0))) +
      scale_y_continuous(trans = "log10", limits = c(0.1, NA)) +
      theme_bw() +
      theme(text = element_text(size = 16),
            axis.title.y = element_text(size = 16),
            strip.text.x = element_text(size = 14),
            strip.background = element_rect(fill = "white"),
            plot.title = element_text(hjust = 0.5),
            legend.position = "none") +
        facet_wrap(~ stove, nrow = 1, scales = "free") +
        xlab("") +
        ylab(expression(paste(PM[2.5], " Emissions Factors (g/kg-fuel)"))) +
        labs(shape = "", color = "")
```

```{r fig_4b_2, fig.width=8, fig.height=3}
p2 <- 
  plot %>%
    ggplot(aes(x = test_type, y = co_ef)) +
      geom_jitter(color = "#0072B2", shape = 1, size = 1.5, stroke = 1.5, width = 0.25) +
      #geom_errorbar(data =  co_summary,
      #              aes(x = test_type, y = mean, ymin = min, ymax = max),
      #              stroke = 1, width = 0.25) +
      scale_color_manual(values = c("#999999", "#E69F00",
                                    "yellowgreen", "darkcyan", "coral3", "#0072B2", "#7b3294")) +
      guides(color = guide_legend(override.aes = list(size = 2,
                                                      shape = 1, linetype = 0))) +
      scale_y_continuous(limits = c(0, NA)) +
      theme_bw() +
      theme(text = element_text(size = 16),
            axis.title.y = element_text(size = 16),
            strip.text.x = element_text(size = 14),
            strip.background = element_rect(fill = "white"),
            plot.title = element_text(hjust = 0.5),
            legend.position = "none") +
        facet_wrap(~ stove, nrow = 1, scales = "free") +
        xlab("") +
        ylab("CO Emissions Factors (g/kg-fuel)") +
        labs(shape = "", color = "")
```

```{r figure_4_ncolor, echo=FALSE, fig.width=12, fig.height=8, dpi=600, dev='pdf'}
  p1 + p2 + plot_layout(ncol = 1, heights = c(1, 1))
```

```{r, fig.width=3, fig.height=3, eval=FALSE}
  plot %>%
    dplyr::filter(grepl("three stone fire|rocket elbow|forced-draft", stove), grepl("FST", test_type)) %>%
    ggplot(aes(x = pm_ef, fill = stove)) +
      geom_histogram() +
      theme_bw() +
      theme(text = element_text(size = 14),
            strip.text.x = element_text(size = 11),
            strip.background = element_rect(fill = "white"),
            plot.title = element_text(hjust = 0.5),
            legend.position = "none") +
        facet_wrap(~ stove, ncol = 1) +
        ylab("Frequency") +
        xlab(expression(paste(PM[2.5], " Emissions Factors (g/kg-fuel)"))) +
        labs(shape = "", color = "")
```

```{r, fig.width=3, fig.height=3, eval=FALSE}
  plot %>%
    dplyr::filter(grepl("three stone fire|rocket elbow|forced-draft", stove), grepl("FST", test_type)) %>%
    ggplot(aes(x = co_ef, fill = stove)) +
      geom_histogram() +
      theme_bw() +
      theme(text = element_text(size = 14),
            strip.text.x = element_text(size = 11),
            strip.background = element_rect(fill = "white"),
            plot.title = element_text(hjust = 0.5),
            legend.position = "none") +
        facet_wrap(~ stove, ncol = 1) +
        ylab("Frequency") +
        xlab("CO Emissions Factors (g/kg-fuel)") +
        labs(shape = "", color = "")
```

