---
title: "Figure 1: temp/firepower models"
output:
  html_document:
    toc: true
    toc_float: true
    theme: paper
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, patchwork, weathermetrics, lme4, MuMIn)
  options(knitr.table.format = "latex")
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path = 'figures/', warning = FALSE,
                        message = FALSE, cache = FALSE)
```

```{r, echo=FALSE}
  samples <- readRDS("../r_files/lab_samples.RDS")
  firepower <- readRDS("../r_files/lab_firepower.RDS")
  flue_temp <- readRDS("../r_files/lab_flue_temp.RDS")
```

```{r}
  flue_temp <-
    flue_temp %>%
    dplyr::mutate(hood = ifelse(grepl("^19B$|^17B$|^14B$|^11B$|^29B$|^22B$|^15B$|^13B$|^1B$|^9B$|^4B$|^12B$|^8B$|^2B$|^18B$|^20B$|^10B$|^7B$|^16B$|^21B$|^3B$|^9C$|^18C$|^13C$|^21C$|^7C$|^19C$|^1C$|^20C$|^2C$|^15C$|^11C$|^15D$|^19D$|^13D", id), "b", "a"))
```

```{r}
  flue_temp <-
    flue_temp %>%
    dplyr::mutate(temp = ifelse(hood == "a", kelvin.to.celsius(temp), temp))
```

```{r}
  amb_temp <- tibble::data_frame(id = c("10B", "10C", "11A", "11C", "12A", "12B",
                                        "12C", "13A", "13B", "13C", "14A", "14C",
                                        "15C", "16A", "16C", "19A", "20A", "20B",
                                        "20C", "21A", "21C", "6A", "8A", "8B",
                                        "8C", "9A", "9B", "9C"),
                                 amb_temp = c(21.6, 29.8, 27.56, 25.6, 29.0, 23.5,
                                              26.15, 28.26, 24.2, 22.7, 29.0, 29.0,
                                              20.3, 33.03, 32.48, 29.0, 31.35, 24.1,
                                              24.7, 28.33, 24.7, 33.88, 28.07, 24.8,
                                              26.15, 28.9, 23.1, 24.9))
```

```{r, eval = FALSE}
  temp_fp <-
    temp_fp %>%
    dplyr::left_join(amb_temp, by = "id") %>%
    dplyr::mutate(temp = temp - amb_temp) %>%
    dplyr::filter(temp > 50) %>%
    dplyr::select(-amb_temp)
```

```{r}
  temp_fp <-
    flue_temp %>%
    left_join(firepower, by = c("id", "date", "time")) %>%
    na.omit %>%
    dplyr::left_join(dplyr::select(samples, id, stove, fuel), by = "id") %>%
    dplyr::filter(grepl("chulha|Rocket|Ceramic plancha", stove))
```

# filter data from tests that don't have full set of data

```{r}
  temp_fp <-
    temp_fp %>%
    dplyr::filter(id != "19C", id != "15A", id != "4C", id != "5A", id != "5C", id != "4B", id != "11A", id != "11C")
```

```{r, fig.height=6, echo=FALSE}
  ggplot(data = temp_fp, aes(x = time, y = temp)) +
    geom_line() +
    facet_wrap(.~id, scales = "free")
```

```{r, fig.height=6, echo=FALSE}
  ggplot(data = temp_fp, aes(x = time, y = firepower)) +
    geom_line() +
    facet_wrap(.~id, scales = "free")
```

```{r, fig.height=6, echo=FALSE}
  ggplot(data = temp_fp, aes(x = temp, y = firepower)) +
    geom_point() +
    facet_wrap(.~id, scales = "free")
```

```{r}
  saveRDS(temp_fp, "../r_files/lab_flue_temp_merged.RDS")
```

