---
title: "Lab metadata qaqc"
output:
  html_document:
    toc: true
    toc_float: true
    theme: paper
---

```{r library, warning=FALSE, message=FALSE, echo=FALSE}
  library(tidyverse)
  library(gridExtra)
  library(knitr)
  library(forcats)  #meow
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', warning=FALSE, message=FALSE, cache=FALSE)
```

# Load files

* Load metadata

```{r load_data}
  samples <- readRDS("../r_files/lab_meta.RDS")
  jetter_data <- readRDS("../r_files/jetter_data.RDS")
```

* functions

```{r load_functions}
  source("../r_scripts/plots.R")
```

# Clean metadata

## Add fuel type

```{r fuel_type}
  samples <-
    samples %>%
    dplyr::mutate(fuel = gsub("Wood Pellets", "Eucalyptus Pellets", fuel),
                  fuel_type = if_else(grepl("Lump Hardwood|Coconut Charcoal", fuel),
                                      "batch-fed\ncharcoal protocol",
                                      "continuous-feed\nwood protocol"),
                  fuel_type = if_else(grepl("Red Oak|Eucalyptus Pellets", fuel),
                                      "batch-fed\nwood protocol", fuel_type),
                  fuel_type = as.factor(fuel_type),
                  fuel_type = fct_relevel(fuel_type,
                                          "continuous-feed\nwood protocol",
                                          "batch-fed\ncharcoal protocol",
                                          "batch-fed\nwood protocol"))
```

## Change to lowercase

```{r}
  samples <-
    samples %>%
    dplyr::mutate(stove = tolower(stove),
                  fuel = tolower(fuel)) %>%
          dplyr::mutate(stove =
                          stove %>%
                          forcats::fct_recode("ceramic charcoal (small)" = "ceramic jiko (small)",
                                              "ceramic charcoal (large)" = "ceramic jiko (large)",
                                              "metal charcoal (small)" = "metal jiko (small)",
                                              "metal charcoal (large)" = "metal jiko (large)",
                                              "insulated charcoal (burn labs)" = "metal jiko (burn)",
                                              "built-in justa (artisan)" = "justa (artisan)",
                                              "built-in justa (envirofit)" = "justa (hm5000)",
                                              "rocket elbow (envirofit)" = "rocket elbow (g3300)"))
```

```{r}
  jetter_data <- 
    jetter_data %>%
    dplyr::mutate(stove = 
                    stove %>%
                    forcats::fct_recode("rocket elbow (envirofit)" = "envirofit g3300",
                                        "metal charcoal (small)" = "metal charcoal",
                                        "ceramic charcoal (small)" = "ceramic charcoal",
                                        "ceramic charcoal (large)" = "gyapa",
                                        "gasifier (philips)" = "philips fan",
                                        "built-in justa (artisan)" = "onil"),
                  protocol =
                    protocol %>%
                    forcats::fct_recode("hot start" = "wbt_hs",
                                        "cold start" = "wbt_cs",
                                        "simmer" = "wbt_sim")) %>%
    dplyr::mutate(stove_cat =
                    forcats::fct_collapse(stove,
                    "traditional stoves" = c("three stone fire",
                                             "ceramic charcoal (small)",
                                             "ceramic charcoal (large)",
                                             "metal charcoal (small)",
                                             "built-in justa (artisan)"),
                    "improved natural draft stoves" = c("rocket elbow (envirofit)"),
                    "improved forced draft stoves" = c("gasifier (philips)")),
                  fuel_type = ifelse(fuel == "charcoal", "batch-fed\ncharcoal protocol", fuel),
                  fuel_type = ifelse(fuel == "wood", "continuous-feed\nwood protocol", fuel_type),
                  fuel_type = ifelse(grepl("gasifier",stove), "batch-fed\nwood protocol", fuel_type),
                  fuel_type = as.factor(fuel_type),
                  fuel_type = fct_relevel(fuel_type,
                                          "continuous-feed\nwood protocol",
                                          "batch-fed\ncharcoal protocol",
                                          "batch-fed\nwood protocol"))
```

## Add stove type

```{r stove_type}
  samples <-
    samples %>%
    dplyr::mutate(stove_cat =
                    forcats::fct_collapse(stove,
                    "traditional stoves" = c("three stone fire",
                                             "sunken pot",
                                             "clay ring",
                                             "ceramic charcoal (small)",
                                             "ceramic charcoal (large)",
                                             "metal charcoal (small)",
                                             "metal charcoal (large)",
                                             "vikram",
                                             "built-in justa (artisan)"),
                    "improved natural draft stoves" = c("insulated charcoal (burn labs)",
                                                        "rocket elbow (envirofit)",
                                                        "rocket elbow (chulika)",
                                                        "built-in justa (envirofit)"),
                    "improved forced draft stoves" = c("gasifier (philips)",
                                                       "gasifier (doe)")))
```

# Plot metadata

## Test grid

```{r test_grid, fig.width=12, fig.height=10, echo=FALSE}
  test_list <- samples %>%
               dplyr::group_by(stove, fuel, fuel_type) %>%
               dplyr::summarise(id = paste(id, collapse = "\n"))

  plot_test_list(test_list, x_var = "stove", y_var = "fuel", id = "id", fill_color = "fuel_type")
```

## Stove-fuel combinations

```{r stove_fuel_hist, fig.width=12, fig.height=8, echo=FALSE}
  p1 <- plot_meta_hist(df = samples, var = "stove")

  p2 <- plot_meta_hist(df = samples, var = "fuel")

  grid.arrange(p1, p2, ncol = 2)
```

```{r save_meta}
  saveRDS(samples, "../r_files/lab_samples.RDS")
  saveRDS(jetter_data, "../r_files/jetter_data.RDS")
```

