---
title: "Load and save data"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', warning=FALSE, message=FALSE, cache=FALSE)
```

```{r library, echo=FALSE}
  library(tidyverse)
  library(forcats)
```

```{r functions, echo=FALSE}
  source("../r_scripts/R_load_data.R")
  source("../r_scripts/R_load_metadata.R")
```

# Field data (raw)

## Thermocouples

```{r load_temp} 
  field_temp <- load_multifile(fldr = "../data/field/temp", inst = "temp")
  saveRDS(field_temp, file = "../r_files/field_temp.rds")
```

## Gravimetric

```{r load_grav} 
```
 
## Data logs

* Load sampling times and household info

```{r metadata} 
  field_meta <- load_meta("field_meta")
  saveRDS(field_meta, file = "../r_files/field_meta.rds")
```

* Load temperature meta data

```{r temp_metadata} 
  field_temp_meta <- load_meta("field_temp_meta")
  saveRDS(field_temp_meta, file = "../r_files/field_temp_meta.rds")
```

* Load notes

```{r temp_metadata} 
  field_notes <- load_meta("field_notes")
  saveRDS(field_notes, file = "../r_files/field_notes.rds")
```

# Lab data (cleaned)
