---
title: "Load and save data"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.path='figures/', warning=FALSE, message=FALSE, cache=FALSE)
```

```{r library, echo=FALSE}
  library(tidyverse)
  library(forcats)
```

```{r functions, echo=FALSE}
  source("../r_scripts/load_data.r")
  source("../r_scripts/load_metadata.r")
```

# Field data (raw)

## Thermocouples

```{r field_temp} 
  field_temp <- load_datafiles(fldr = "../data/field/temp", inst = "temp")
  saveRDS(field_temp, file = "../r_files/field_temp.rds")
```

## SUMs

```{r field_sums} 
  field_sums <- load_datafiles(fldr = "../data/field/sums", inst = "sums")
  saveRDS(field_sums, file = "../r_files/field_sums.rds")
```

## Gravimetric

```{r field_grav} 
  field_grav <- load_datafiles(fldr = "../data/field/grav", inst = "grav")
  saveRDS(field_grav, file = "../r_files/field_grav.rds")
```

## Gas analyzer

```{r field_aqe} 
  field_aqe <- load_datafiles(fldr = "../data/field/aqe", inst = "aqe")
  saveRDS(field_aqe, file = "../r_files/field_aqe.rds")
```
 
## Data logs

* Load sampling times and household info

```{r field_metadata} 
  field_meta <- load_meta("field_meta")
  saveRDS(field_meta, file = "../r_files/field_meta.rds")
```

* Load flow rate data

```{r field_flows} 
  field_flows <- load_meta("field_flows")
  saveRDS(field_flows, file = "../r_files/field_flows.rds")
```

* Load filter meta data

```{r field_filter_meta} 
  field_filter_meta <- load_meta("field_filter_meta")
  saveRDS(field_filter_meta, file = "../r_files/field_filter_meta.rds")
```

* Load temperature meta data

```{r field_temp_meta} 
  field_temp_meta <- load_meta("field_temp_meta")
  saveRDS(field_temp_meta, file = "../r_files/field_temp_meta.rds")
```

* Load notes

```{r field_notes} 
  field_notes <- load_meta("field_notes")
  saveRDS(field_notes, file = "../r_files/field_notes.rds")
```

* Load fuel weights

```{r field_fuel_wgts} 
  field_fuel <- load_meta("field_fuel")
  saveRDS(field_fuel, file = "../r_files/field_fuel_wgts.rds")
```

* Load test events

```{r field_events} 
  field_events <- load_meta("field_events")
  saveRDS(field_events, file = "../r_files/field_events.rds")
```

# Lab data (cleaned)
