---
title: "Calculate emission factors"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, kableExtra)
```

```{r global_options, echo=FALSE}
  knitr::opts_chunk$set(fig.path ='figures/',
                        warning = FALSE, message = FALSE, cache = FALSE)
```

# tidy data

load data

```{r}
  samples <- readRDS("../../../r_files/lab_samples.RDS")
  fuel_properties <- readRDS("../../../r_files/fuel_properties.RDS")
  emissions <- readRDS("../../../r_files/lab_emissions.RDS")
  #energy <- readRDS("../../r_data/energy.RDS")
  fuel_properties <- readRDS("../../../r_files/fuel_properties.RDS")
```

# calculate fuel mass

```{r}
  fuel <-
    emissions %>%
    dplyr::filter(pol == "co2" | pol == "co") %>%
    dplyr::filter(metric == "mass_carbon") %>%
    dplyr::select(id, pol, val, datetime, date, time) %>%
    tidyr::spread(pol, val) %>%
    dplyr::filter(!is.na(co2)) %>%
    tidyr::gather(pol, val, 5:ncol(.)) %>%
    dplyr::group_by(id, datetime, date, time) %>%
    dplyr::summarise(mass_carbon = sum(val, na.rm = TRUE) * 1e-6) %>%
    dplyr::left_join(dplyr::select(samples, id, fuel), by = "id") %>%
    dplyr::left_join(fuel_properties, by = "fuel") %>%
    dplyr::mutate(mass_fuel_c = mass_carbon * (1 / carbon_fraction)) %>%
    dplyr::select(id, mass_fuel_c, datetime, date, time) %>%
    dplyr::left_join(dplyr::select(samples, id, stove, fuel), by = "id") %>%
    dplyr::left_join(fuel_properties, by = "fuel")
```

# mass of fuel emissions factor

```{r, echo=TRUE} 
  mass_fuel <- 
    emissions %>%
    dplyr::filter(metric == "mass_emitted") %>%
    dplyr::inner_join(fuel %>%
                        dplyr::filter(!is.na(mass_fuel_c)), by = c("id", "datetime", "time", "date")) %>%
    dplyr::mutate(val =  (val * 1e-3) / (mass_fuel_c * 1e-3)) %>%
    dplyr::select(id, pol, val, bg, datetime, date, time) %>%
    dplyr::mutate(units = "miligrams per kilogram fuel",
                  units = ifelse(pol == "ultrafines", "number per kilogram fuel", units),
                  val = ifelse(pol == "ultrafines", val * 1e3, val),
                  metric = "mass_fuel_ef")
```

## plot: average emissions factor

```{r, echo=FALSE, fig.height=12, fig.width=12}
  mass_fuel_p <-
    mass_fuel %>%
    dplyr::left_join(dplyr::select(samples, id, stove, fuel), by = "id")

 mass_fuel_p %>%
    dplyr::group_by(id, pol) %>%
    dplyr::summarise(val = mean(val, na.rm = TRUE)) %>%
    ggplot(aes_string(x = "id", y = "val")) +
      geom_point() + 
      theme_bw() +
      theme(text = element_text(size = 16),
            legend.position = "top") +
      facet_wrap(~pol, scales = "free") +
      ylab("emission factor (mg/kg)") +
      xlab("")
```

# mass of fuel emissions factor

```{r, echo=TRUE} 
  energy_fuel <- 
    emissions %>%
    dplyr::filter(metric == "mass_emitted") %>%
    dplyr::inner_join(fuel %>%
                       dplyr::filter(!is.na(mass_fuel_c)), by = c("id", "datetime", "time", "date")) %>%
    dplyr::mutate(val =  (val * 1e-3) / ((mass_fuel_c * 1e-3) * (lhv * 1e-3))) %>%
    dplyr::select(id, pol, val, bg, datetime, date, time) %>%
    dplyr::mutate(units = "miligrams per Megajoule fuel",
                  units = ifelse(pol == "ultrafines", "number per Megajoule fuel", units),
                  val = ifelse(pol == "ultrafines", val * 1e3, val),
                  metric = "energy_fuel_ef")
```

# energy of fuel emissions factor

```{r,eval=FALSE}
  energy_factors <-
    emissions %>%
    dplyr::filter(metric == "mass_emitted") %>%
    dplyr::inner_join(energy %>%
                        dplyr::filter(!is.na(joules)), by = "id") %>%
    dplyr::mutate(val =  (val * 1e-3) / (joules * 1e-6)) %>% 
    dplyr::select(id, pol, pol_category, val, qc, bg, lod) %>%
    dplyr::mutate(units = "miligrams per Megajoule delivered",
                  units = ifelse(pol == "ultrafines", "number per Megajoule delivered", units),
                  val = ifelse(pol == "ultrafines", val * 1e3, val),
                  metric = "energy_delivered_ef")
```

# emissions rate

```{r}
  emissions_rate <-
    emissions %>%
    dplyr::filter(metric == "mass_emitted") %>%
    dplyr::mutate(val =  (val * 1e-3) / (3 * 60),
                  val = val * 60 * 60) %>% 
    dplyr::select(id, pol, val, bg, datetime, date, time) %>%
    dplyr::mutate(units = "miligrams per hour",
                  units = ifelse(pol == "ultrafines", "number per hour", units),
                  val = ifelse(pol == "ultrafines", val * 1e3, val),
                  metric = "emissions_rate")
```

## table: number of data points (by pollutant)

```{r, echo=FALSE,eval=FALSE}
  energy_factors %>%
    dplyr::filter(metric == "energy_delivered_ef") %>%
    dplyr::group_by(pol) %>%
    dplyr::do(val = nrow(.)) %>%
    dplyr::mutate(val = cell_spec(val, "html", color = ifelse(val < 10, "red", "blue"))) %>%
    dplyr::arrange(val) %>%
    knitr::kable("markdown", align = 'c')
```

```{r}
  emissions_factors <-
    mass_fuel %>%
    dplyr::bind_rows(energy_fuel) %>%
    #dplyr::bind_rows(energy_factors) %>%
    dplyr::bind_rows(emissions_rate)
```

# save

```{r}
  saveRDS(emissions_factors, file = "../../../r_files/lab_emissions_factors.RDS")
```

```{r}
  emissions_factors %>%
    dplyr::left_join(samples, by = "id") %>%
    dplyr::select(id, stove, fuel) %>%
    dplyr::distinct() %>%
    dplyr::group_by(stove, fuel) %>%
    dplyr::summarise(n = n())
```

